import type { CommitCandidate, DiffLine, PullResult, Repo, RepoDetail } from './types';

/* auto-generated by npm run sync:data */
export const SCANNED_AT = "2026/7/1 09:59:41";
export const CATEGORIES: string[] = [
  "GitHub 工作区",
  "本地项目"
];
export const REPOS: Repo[] = [
  {
    "id": "git-monorepo-tools-5b123e",
    "name": "git-monorepo-tools",
    "branch": "master",
    "path": "E:/github/git-monorepo-tools",
    "remote": "origin",
    "category": "GitHub 工作区",
    "modified": 29,
    "ahead": 0,
    "behind": 0,
    "conflicts": 0,
    "status": "changed",
    "lastScan": "09:59:41",
    "files": [
      {
        "id": ".codestable/goals/2026-06-30-git-manager-ui-clone/functional-acceptance.md::unstaged",
        "status": "A",
        "path": ".codestable/goals/2026-06-30-git-manager-ui-clone/functional-acceptance.md",
        "additions": 48,
        "deletions": 0,
        "size": "1.3 KB",
        "staged": false
      },
      {
        "id": ".codestable/goals/2026-06-30-git-manager-ui-clone/goal.md::unstaged",
        "status": "A",
        "path": ".codestable/goals/2026-06-30-git-manager-ui-clone/goal.md",
        "additions": 44,
        "deletions": 0,
        "size": "1.3 KB",
        "staged": false
      },
      {
        "id": ".codestable/goals/2026-06-30-git-manager-ui-clone/iterations/001-page.png::unstaged",
        "status": "A",
        "path": ".codestable/goals/2026-06-30-git-manager-ui-clone/iterations/001-page.png",
        "additions": 1550,
        "deletions": 0,
        "size": "349.7 KB",
        "staged": false
      },
      {
        "id": ".codestable/goals/2026-06-30-git-manager-ui-clone/iterations/001.md::unstaged",
        "status": "A",
        "path": ".codestable/goals/2026-06-30-git-manager-ui-clone/iterations/001.md",
        "additions": 44,
        "deletions": 0,
        "size": "1.6 KB",
        "staged": false
      },
      {
        "id": ".codestable/goals/2026-06-30-git-manager-ui-clone/iterations/002.md::unstaged",
        "status": "A",
        "path": ".codestable/goals/2026-06-30-git-manager-ui-clone/iterations/002.md",
        "additions": 50,
        "deletions": 0,
        "size": "1.7 KB",
        "staged": false
      },
      {
        "id": ".codestable/goals/2026-06-30-git-manager-ui-clone/state.yaml::unstaged",
        "status": "A",
        "path": ".codestable/goals/2026-06-30-git-manager-ui-clone/state.yaml",
        "additions": 25,
        "deletions": 0,
        "size": "1014 B",
        "staged": false
      },
      {
        "id": "index.html::unstaged",
        "status": "A",
        "path": "index.html",
        "additions": 14,
        "deletions": 0,
        "size": "350 B",
        "staged": false
      },
      {
        "id": "package-lock.json::unstaged",
        "status": "A",
        "path": "package-lock.json",
        "additions": 1917,
        "deletions": 0,
        "size": "61.8 KB",
        "staged": false
      },
      {
        "id": "package.json::unstaged",
        "status": "A",
        "path": "package.json",
        "additions": 26,
        "deletions": 0,
        "size": "601 B",
        "staged": false
      },
      {
        "id": "scripts/sync-real-data.mjs::unstaged",
        "status": "A",
        "path": "scripts/sync-real-data.mjs",
        "additions": 493,
        "deletions": 0,
        "size": "16.3 KB",
        "staged": false
      },
      {
        "id": "src/app/App.tsx::unstaged",
        "status": "A",
        "path": "src/app/App.tsx",
        "additions": 111,
        "deletions": 0,
        "size": "3.4 KB",
        "staged": false
      },
      {
        "id": "src/app/components/ai-commit-panel.tsx::unstaged",
        "status": "A",
        "path": "src/app/components/ai-commit-panel.tsx",
        "additions": 381,
        "deletions": 0,
        "size": "12.3 KB",
        "staged": false
      },
      {
        "id": "src/app/components/common.tsx::unstaged",
        "status": "A",
        "path": "src/app/components/common.tsx",
        "additions": 62,
        "deletions": 0,
        "size": "1.2 KB",
        "staged": false
      },
      {
        "id": "src/app/components/diff-list.tsx::unstaged",
        "status": "A",
        "path": "src/app/components/diff-list.tsx",
        "additions": 352,
        "deletions": 0,
        "size": "12.1 KB",
        "staged": false
      },
      {
        "id": "src/app/components/diff-preview.tsx::unstaged",
        "status": "A",
        "path": "src/app/components/diff-preview.tsx",
        "additions": 173,
        "deletions": 0,
        "size": "6.7 KB",
        "staged": false
      },
      {
        "id": "src/app/components/pull-all-drawer.tsx::unstaged",
        "status": "A",
        "path": "src/app/components/pull-all-drawer.tsx",
        "additions": 180,
        "deletions": 0,
        "size": "7.7 KB",
        "staged": false
      },
      {
        "id": "src/app/components/settings-modal.tsx::unstaged",
        "status": "A",
        "path": "src/app/components/settings-modal.tsx",
        "additions": 497,
        "deletions": 0,
        "size": "16.6 KB",
        "staged": false
      },
      {
        "id": "src/app/components/sidebar.tsx::unstaged",
        "status": "A",
        "path": "src/app/components/sidebar.tsx",
        "additions": 394,
        "deletions": 0,
        "size": "13.1 KB",
        "staged": false
      },
      {
        "id": "src/app/components/workspace.tsx::unstaged",
        "status": "A",
        "path": "src/app/components/workspace.tsx",
        "additions": 393,
        "deletions": 0,
        "size": "15.8 KB",
        "staged": false
      },
      {
        "id": "src/app/data.ts::unstaged",
        "status": "A",
        "path": "src/app/data.ts",
        "additions": 2113,
        "deletions": 0,
        "size": "56.3 KB",
        "staged": false
      },
      {
        "id": "src/app/theme.ts::unstaged",
        "status": "A",
        "path": "src/app/theme.ts",
        "additions": 25,
        "deletions": 0,
        "size": "576 B",
        "staged": false
      },
      {
        "id": "src/app/types.ts::unstaged",
        "status": "A",
        "path": "src/app/types.ts",
        "additions": 100,
        "deletions": 0,
        "size": "1.9 KB",
        "staged": false
      },
      {
        "id": "src/main.tsx::unstaged",
        "status": "A",
        "path": "src/main.tsx",
        "additions": 6,
        "deletions": 0,
        "size": "168 B",
        "staged": false
      },
      {
        "id": "src/styles/fonts.css::unstaged",
        "status": "A",
        "path": "src/styles/fonts.css",
        "additions": 2,
        "deletions": 0,
        "size": "136 B",
        "staged": false
      },
      {
        "id": "src/styles/index.css::unstaged",
        "status": "A",
        "path": "src/styles/index.css",
        "additions": 73,
        "deletions": 0,
        "size": "940 B",
        "staged": false
      },
      {
        "id": "src/vite-env.d.ts::unstaged",
        "status": "A",
        "path": "src/vite-env.d.ts",
        "additions": 2,
        "deletions": 0,
        "size": "38 B",
        "staged": false
      },
      {
        "id": "tsconfig.json::unstaged",
        "status": "A",
        "path": "tsconfig.json",
        "additions": 23,
        "deletions": 0,
        "size": "616 B",
        "staged": false
      },
      {
        "id": "tsconfig.node.json::unstaged",
        "status": "A",
        "path": "tsconfig.node.json",
        "additions": 13,
        "deletions": 0,
        "size": "250 B",
        "staged": false
      },
      {
        "id": "vite.config.ts::unstaged",
        "status": "A",
        "path": "vite.config.ts",
        "additions": 10,
        "deletions": 0,
        "size": "174 B",
        "staged": false
      }
    ],
    "stagedCount": 0,
    "unstagedCount": 29,
    "scannedAt": "2026/7/1 09:59:41",
    "history": [
      {
        "hash": "0237c860ccf31373d664665feda79d7d3d253ba3",
        "shortHash": "0237c86",
        "author": "xiakunming",
        "time": "14 hours ago",
        "message": "init",
        "additions": 9513,
        "deletions": 0
      }
    ]
  },
  {
    "id": "dschat-5182d3",
    "name": "dsChat",
    "branch": "master",
    "path": "E:/github/dsChat",
    "remote": "origin",
    "category": "GitHub 工作区",
    "modified": 19,
    "ahead": 0,
    "behind": 0,
    "conflicts": 0,
    "status": "changed",
    "lastScan": "09:59:41",
    "files": [
      {
        "id": ".codestable/architecture/ARCHITECTURE.md::unstaged",
        "status": "A",
        "path": ".codestable/architecture/ARCHITECTURE.md",
        "additions": 15,
        "deletions": 0,
        "size": "229 B",
        "staged": false
      },
      {
        "id": ".codestable/attention.md::unstaged",
        "status": "A",
        "path": ".codestable/attention.md",
        "additions": 22,
        "deletions": 0,
        "size": "404 B",
        "staged": false
      },
      {
        "id": ".codestable/compound/.gitkeep::unstaged",
        "status": "A",
        "path": ".codestable/compound/.gitkeep",
        "additions": 2,
        "deletions": 0,
        "size": "1 B",
        "staged": false
      },
      {
        "id": ".codestable/features/2026-05-24-tool-calling/tool-calling-design.md::unstaged",
        "status": "A",
        "path": ".codestable/features/2026-05-24-tool-calling/tool-calling-design.md",
        "additions": 261,
        "deletions": 0,
        "size": "9.2 KB",
        "staged": false
      },
      {
        "id": ".codestable/issues/.gitkeep::unstaged",
        "status": "A",
        "path": ".codestable/issues/.gitkeep",
        "additions": 2,
        "deletions": 0,
        "size": "1 B",
        "staged": false
      },
      {
        "id": ".codestable/reference/code-dimensions.md::unstaged",
        "status": "A",
        "path": ".codestable/reference/code-dimensions.md",
        "additions": 98,
        "deletions": 0,
        "size": "4.8 KB",
        "staged": false
      },
      {
        "id": ".codestable/reference/maintainer-notes.md::unstaged",
        "status": "A",
        "path": ".codestable/reference/maintainer-notes.md",
        "additions": 50,
        "deletions": 0,
        "size": "2.6 KB",
        "staged": false
      },
      {
        "id": ".codestable/reference/requirement-example.md::unstaged",
        "status": "A",
        "path": ".codestable/reference/requirement-example.md",
        "additions": 89,
        "deletions": 0,
        "size": "3.2 KB",
        "staged": false
      },
      {
        "id": ".codestable/reference/shared-conventions.md::unstaged",
        "status": "A",
        "path": ".codestable/reference/shared-conventions.md",
        "additions": 253,
        "deletions": 0,
        "size": "15.1 KB",
        "staged": false
      },
      {
        "id": ".codestable/reference/system-overview.md::unstaged",
        "status": "A",
        "path": ".codestable/reference/system-overview.md",
        "additions": 115,
        "deletions": 0,
        "size": "7.6 KB",
        "staged": false
      },
      {
        "id": ".codestable/reference/tools.md::unstaged",
        "status": "A",
        "path": ".codestable/reference/tools.md",
        "additions": 101,
        "deletions": 0,
        "size": "5.7 KB",
        "staged": false
      },
      {
        "id": ".codestable/requirements/.gitkeep::unstaged",
        "status": "A",
        "path": ".codestable/requirements/.gitkeep",
        "additions": 2,
        "deletions": 0,
        "size": "1 B",
        "staged": false
      },
      {
        "id": ".codestable/roadmap/.gitkeep::unstaged",
        "status": "A",
        "path": ".codestable/roadmap/.gitkeep",
        "additions": 2,
        "deletions": 0,
        "size": "1 B",
        "staged": false
      },
      {
        "id": ".codestable/tools/search-yaml.py::unstaged",
        "status": "A",
        "path": ".codestable/tools/search-yaml.py",
        "additions": 339,
        "deletions": 0,
        "size": "12.7 KB",
        "staged": false
      },
      {
        "id": ".codestable/tools/validate-yaml.py::unstaged",
        "status": "A",
        "path": ".codestable/tools/validate-yaml.py",
        "additions": 316,
        "deletions": 0,
        "size": "11.0 KB",
        "staged": false
      },
      {
        "id": ".gitignore::unstaged",
        "status": "A",
        "path": ".gitignore",
        "additions": 1,
        "deletions": 0,
        "size": "298 B",
        "staged": false
      },
      {
        "id": "docs/tool-calling-architecture.md::unstaged",
        "status": "D",
        "path": "docs/tool-calling-architecture.md",
        "additions": 0,
        "deletions": 260,
        "size": "—",
        "staged": false
      },
      {
        "id": "src/styles/chat-composer-preview.css::unstaged",
        "status": "A",
        "path": "src/styles/chat-composer-preview.css",
        "additions": 39,
        "deletions": 0,
        "size": "716 B",
        "staged": false
      },
      {
        "id": "src/styles/chat-composer.css::unstaged",
        "status": "M",
        "path": "src/styles/chat-composer.css",
        "additions": 158,
        "deletions": 141,
        "size": "6.8 KB",
        "staged": false
      }
    ],
    "stagedCount": 0,
    "unstagedCount": 19,
    "scannedAt": "2026/7/1 09:59:41",
    "history": [
      {
        "hash": "28a22e6968e3901c48cca25b9eee59e1a82b6a61",
        "shortHash": "28a22e6",
        "author": "xiakunming",
        "time": "5 weeks ago",
        "message": "fix(session): restore idle reset on plugin reopen",
        "additions": 163,
        "deletions": 38
      },
      {
        "hash": "a2d943f981c9b5074ae94f5d9a44bd5b2c5fc2fc",
        "shortHash": "a2d943f",
        "author": "夏坤明",
        "time": "6 weeks ago",
        "message": "refactor(ui): 重构代码块复制按钮 DOM 结构并优化高亮降级逻辑",
        "additions": 80,
        "deletions": 31
      },
      {
        "hash": "edea5933a940935cfb84eb196945f5fcb0101aa3",
        "shortHash": "edea593",
        "author": "xiakunming",
        "time": "6 weeks ago",
        "message": "feat(ui): 实现消息复制成功动画及服务商删除确认弹窗",
        "additions": 241,
        "deletions": 31
      },
      {
        "hash": "f726c72097c8a529e4a1af3bbbd6daaccfa8d7d0",
        "shortHash": "f726c72",
        "author": "xiakunming",
        "time": "6 weeks ago",
        "message": "refactor(tools): 移除 OpenAI 原生搜索开关，重构工具调用协议校验",
        "additions": 139,
        "deletions": 74
      },
      {
        "hash": "4bccd4a660b81769dc8f1365515b7b2620cdf3f7",
        "shortHash": "4bccd4a",
        "author": "xiakunming",
        "time": "6 weeks ago",
        "message": "feat(settings): 实现服务商能力可编辑系统",
        "additions": 908,
        "deletions": 216
      }
    ]
  },
  {
    "id": "codestable-155430",
    "name": "CodeStable",
    "branch": "main",
    "path": "E:/github/CodeStable",
    "remote": "origin",
    "category": "GitHub 工作区",
    "modified": 6,
    "ahead": 0,
    "behind": 0,
    "conflicts": 0,
    "status": "changed",
    "lastScan": "09:59:41",
    "files": [
      {
        "id": ".codegraph/.gitignore::unstaged",
        "status": "A",
        "path": ".codegraph/.gitignore",
        "additions": 6,
        "deletions": 0,
        "size": "229 B",
        "staged": false
      },
      {
        "id": ".codegraph/codegraph.db::unstaged",
        "status": "A",
        "path": ".codegraph/codegraph.db",
        "additions": 3354,
        "deletions": 0,
        "size": "756.0 KB",
        "staged": false
      },
      {
        "id": ".codegraph/codegraph.db-shm::unstaged",
        "status": "A",
        "path": ".codegraph/codegraph.db-shm",
        "additions": 1,
        "deletions": 0,
        "size": "32.0 KB",
        "staged": false
      },
      {
        "id": ".codegraph/codegraph.db-wal::unstaged",
        "status": "A",
        "path": ".codegraph/codegraph.db-wal",
        "additions": 0,
        "deletions": 0,
        "size": "—",
        "staged": false
      },
      {
        "id": ".codegraph/daemon.log::unstaged",
        "status": "A",
        "path": ".codegraph/daemon.log",
        "additions": 3,
        "deletions": 0,
        "size": "184 B",
        "staged": false
      },
      {
        "id": ".codegraph/daemon.pid::unstaged",
        "status": "A",
        "path": ".codegraph/daemon.pid",
        "additions": 7,
        "deletions": 0,
        "size": "130 B",
        "staged": false
      }
    ],
    "stagedCount": 0,
    "unstagedCount": 6,
    "scannedAt": "2026/7/1 09:59:41",
    "history": [
      {
        "hash": "5377548f4aa7ccfe934b418853b5c28dce293b27",
        "shortHash": "5377548",
        "author": "liuzhengdong",
        "time": "8 weeks ago",
        "message": "feat: Add simphtml.py for enhanced HTML optimization and analysis",
        "additions": 2920,
        "deletions": 0
      },
      {
        "hash": "9216e88d1749830a1d31b6f730798b52f1a4715b",
        "shortHash": "9216e88",
        "author": "liuzhengdong",
        "time": "8 weeks ago",
        "message": "Refactor CodeStable documentation and scripts for improved clarity and structure",
        "additions": 581,
        "deletions": 416
      },
      {
        "hash": "2f44a363407f3858f8c476375c9a7c31f0e93f17",
        "shortHash": "2f44a36",
        "author": "liuzhengdong",
        "time": "9 weeks ago",
        "message": "feat: update case classification and discussion guidelines in cs-brainstorm for improved clarity and structure",
        "additions": 142,
        "deletions": 74
      },
      {
        "hash": "f8c9045adce1ae1ac826068d2034dc62e58d83f1",
        "shortHash": "f8c9045",
        "author": "liuzhengdong",
        "time": "9 weeks ago",
        "message": "feat: refine pre-action guidelines in cs-brainstorm, cs-feat-design, cs-feat-ff, and cs-issue-analyze skills for improved clarity and consistency",
        "additions": 24,
        "deletions": 33
      },
      {
        "hash": "871949be929d3a7e5b5f5b06883d2ae9a817da2a",
        "shortHash": "871949b",
        "author": "liuzhengdong",
        "time": "9 weeks ago",
        "message": "feat: add cs-audit skill and reference templates for system auditing capabilities",
        "additions": 274,
        "deletions": 1
      }
    ]
  },
  {
    "id": "projectnexus-92f7aa",
    "name": "ProjectNexus",
    "branch": "main",
    "path": "E:/github/ProjectNexus",
    "remote": "origin",
    "category": "GitHub 工作区",
    "modified": 2,
    "ahead": 0,
    "behind": 0,
    "conflicts": 0,
    "status": "changed",
    "lastScan": "09:59:41",
    "files": [
      {
        "id": ".codegraph/.gitignore::unstaged",
        "status": "M",
        "path": ".codegraph/.gitignore",
        "additions": 5,
        "deletions": 16,
        "size": "229 B",
        "staged": false
      },
      {
        "id": "package-lock.json::unstaged",
        "status": "A",
        "path": "package-lock.json",
        "additions": 1,
        "deletions": 0,
        "size": "581.8 KB",
        "staged": false
      }
    ],
    "stagedCount": 0,
    "unstagedCount": 2,
    "scannedAt": "2026/7/1 09:59:41",
    "history": [
      {
        "hash": "1aba22a030e4796b84f380572f12d1127ff09173",
        "shortHash": "1aba22a",
        "author": "xiakunming",
        "time": "13 days ago",
        "message": "fix(domain): IdGenerator 改用 crypto.randomUUID，消除碰撞与弃用 API",
        "additions": 54,
        "deletions": 1
      },
      {
        "hash": "161961c294e9fecd2df9ffa76ea49abc8cfd062c",
        "shortHash": "161961c",
        "author": "xiakunming",
        "time": "13 days ago",
        "message": "fix(sync): 分片拉取在校验和相等但字节数不同时仍拉取",
        "additions": 163,
        "deletions": 1
      },
      {
        "hash": "c462dc5db7508040ea059f9976d1918383670138",
        "shortHash": "c462dc5",
        "author": "xiakunming",
        "time": "13 days ago",
        "message": "fix(sync): 初始化后回填冲突基线，修复新用户首写误报冲突",
        "additions": 65,
        "deletions": 14
      },
      {
        "hash": "6828da9bd5aba390990f33b7493c8aa2ccee4da6",
        "shortHash": "6828da9",
        "author": "xiakunming",
        "time": "13 days ago",
        "message": "docs(audit): 记录核心同步引擎与安全模块审计发现",
        "additions": 408,
        "deletions": 0
      },
      {
        "hash": "4f119692daef110c6ce694c0b518ae5f17c93b60",
        "shortHash": "4f11969",
        "author": "夏坤明",
        "time": "13 days ago",
        "message": "docs(ARCHITECTURE.md): 更新架构文档以准确反映 2026-03 边界重构",
        "additions": 73,
        "deletions": 31
      }
    ]
  },
  {
    "id": "codex-history-clear-786b96",
    "name": "codex-history-clear",
    "branch": "master",
    "path": "E:/github/codex-history-clear",
    "remote": "origin",
    "category": "GitHub 工作区",
    "modified": 1,
    "ahead": 0,
    "behind": 0,
    "conflicts": 0,
    "status": "changed",
    "lastScan": "09:59:41",
    "files": [
      {
        "id": "frontend/package.json.md5::unstaged",
        "status": "M",
        "path": "frontend/package.json.md5",
        "additions": 1,
        "deletions": 1,
        "size": "32 B",
        "staged": false
      }
    ],
    "stagedCount": 0,
    "unstagedCount": 1,
    "scannedAt": "2026/7/1 09:59:41",
    "history": [
      {
        "hash": "7ec2b0f09c651e0657d81b310653a95625ab130b",
        "shortHash": "7ec2b0f",
        "author": "夏坤明",
        "time": "12 hours ago",
        "message": "feat(discovery): 实现 rollout 元数据富化与扫描过滤",
        "additions": 716,
        "deletions": 14
      },
      {
        "hash": "986df0bb7f47f8b076652d03a92c8360993cd593",
        "shortHash": "986df0b",
        "author": "夏坤明",
        "time": "12 hours ago",
        "message": "feat(planning): 实现重复分组与删除计划功能",
        "additions": 1635,
        "deletions": 220
      },
      {
        "hash": "6c922082be5e9ed3de23dd01af1240dc7d48d2d6",
        "shortHash": "6c92208",
        "author": "xiakunming",
        "time": "14 hours ago",
        "message": "refactor: remove obsolete scan logic",
        "additions": 87,
        "deletions": 692
      },
      {
        "hash": "1e59d85bf091a2a2eb3d2ad42d1cbce930f03693",
        "shortHash": "1e59d85",
        "author": "xiakunming",
        "time": "16 hours ago",
        "message": "refactor: simplify scan workflow ui",
        "additions": 432,
        "deletions": 288
      },
      {
        "hash": "e91acf29cd08b9cc0c379c923f2dafe3e4979826",
        "shortHash": "e91acf2",
        "author": "xiakunming",
        "time": "16 hours ago",
        "message": "docs: approve reviewed feature designs",
        "additions": 5,
        "deletions": 5
      }
    ]
  },
  {
    "id": "fusi-tools-6e0ef6",
    "name": "fusi-tools",
    "branch": "master",
    "path": "E:/github/fusi-tools",
    "remote": "origin",
    "category": "GitHub 工作区",
    "modified": 1,
    "ahead": 0,
    "behind": 0,
    "conflicts": 0,
    "status": "changed",
    "lastScan": "09:59:41",
    "files": [
      {
        "id": ".codestable/features/.gitkeep::unstaged",
        "status": "A",
        "path": ".codestable/features/.gitkeep",
        "additions": 2,
        "deletions": 0,
        "size": "2 B",
        "staged": false
      }
    ],
    "stagedCount": 0,
    "unstagedCount": 1,
    "scannedAt": "2026/7/1 09:59:41",
    "history": [
      {
        "hash": "eacfb5559395198e45837d4987aad9ee93490864",
        "shortHash": "eacfb55",
        "author": "xiakunming",
        "time": "6 days ago",
        "message": "fix(resourceManager): auto-dismiss file copy notification",
        "additions": 7,
        "deletions": 1
      },
      {
        "hash": "b6c368749fca65f15c63561d6b6bb1635dd3616c",
        "shortHash": "b6c3687",
        "author": "夏坤明",
        "time": "2 weeks ago",
        "message": "feat(docs): 创建 CodeStable 项目管理体系",
        "additions": 1488,
        "deletions": 255
      },
      {
        "hash": "e64f8082e464b5f1acdfc5b1d76af02f0993f28e",
        "shortHash": "e64f808",
        "author": "xixifu",
        "time": "8 weeks ago",
        "message": "config: 将所有模块的 activationEvents 合并为 onStartupFinished",
        "additions": 135,
        "deletions": 171
      },
      {
        "hash": "acc79b233d1773f78170a94a98259b6306cf91d3",
        "shortHash": "acc79b2",
        "author": "xixifu",
        "time": "9 weeks ago",
        "message": "fix(aiCommit): update DeepSeek v4 model mapping",
        "additions": 161,
        "deletions": 27
      },
      {
        "hash": "8075b68f3f4bdea54161cd765199f65bf54b766e",
        "shortHash": "8075b68",
        "author": "xixifu",
        "time": "3 months ago",
        "message": "refactor(ui): silence instant success notifications",
        "additions": 94,
        "deletions": 26
      }
    ]
  },
  {
    "id": "logcat-6d4a4e",
    "name": "logcat",
    "branch": "master",
    "path": "E:/github/logcat",
    "remote": "origin",
    "category": "GitHub 工作区",
    "modified": 1,
    "ahead": 0,
    "behind": 0,
    "conflicts": 0,
    "status": "changed",
    "lastScan": "09:59:41",
    "files": [
      {
        "id": "frontend/package.json.md5::unstaged",
        "status": "M",
        "path": "frontend/package.json.md5",
        "additions": 1,
        "deletions": 1,
        "size": "32 B",
        "staged": false
      }
    ],
    "stagedCount": 0,
    "unstagedCount": 1,
    "scannedAt": "2026/7/1 09:59:41",
    "history": [
      {
        "hash": "805f27aa868950e0de46742374fc648cb95577d1",
        "shortHash": "805f27a",
        "author": "夏坤明",
        "time": "12 days ago",
        "message": "slim focused selection snapshot payload",
        "additions": 88,
        "deletions": 16
      },
      {
        "hash": "8b7f091fd9ec699932fd29699757dfd1ea4973cb",
        "shortHash": "8b7f091",
        "author": "夏坤明",
        "time": "12 days ago",
        "message": "speed up visible selection lookups",
        "additions": 120,
        "deletions": 8
      },
      {
        "hash": "b9c77b854408967220f01a82fe39238f58cc7d92",
        "shortHash": "b9c77b8",
        "author": "夏坤明",
        "time": "12 days ago",
        "message": "speed up focused snapshot lookup",
        "additions": 67,
        "deletions": 6
      },
      {
        "hash": "aff962842db75af468b3b0dde46a26da2b553c24",
        "shortHash": "aff9628",
        "author": "夏坤明",
        "time": "12 days ago",
        "message": "remove rebuild selection scratch alloc",
        "additions": 61,
        "deletions": 1
      },
      {
        "hash": "ec01918237feee0b6bae5af4b2d3bcbc366d3fd8",
        "shortHash": "ec01918",
        "author": "夏坤明",
        "time": "12 days ago",
        "message": "speed up selection patch apply path",
        "additions": 327,
        "deletions": 14
      }
    ]
  },
  {
    "id": "codepocket-71cb72",
    "name": "CodePocket",
    "branch": "main",
    "path": "E:/github/CodePocket",
    "remote": "origin",
    "category": "GitHub 工作区",
    "modified": 0,
    "ahead": 0,
    "behind": 0,
    "conflicts": 0,
    "status": "clean",
    "lastScan": "09:59:41",
    "files": [],
    "stagedCount": 0,
    "unstagedCount": 0,
    "scannedAt": "2026/7/1 09:59:41",
    "history": [
      {
        "hash": "53afd9355395b216fdb3552919b9dc20500d24d1",
        "shortHash": "53afd93",
        "author": "xixifu",
        "time": "6 months ago",
        "message": "feat(manifest): 添加多尺寸图标并格式化清单",
        "additions": 19,
        "deletions": 6
      },
      {
        "hash": "bf0d2d21e6bb520bf995580f3cef2b09081a8f3d",
        "shortHash": "bf0d2d2",
        "author": "夏坤明",
        "time": "6 months ago",
        "message": "feat: 设置变更，允许保存后自动运行",
        "additions": 219,
        "deletions": 152
      },
      {
        "hash": "d8bb0773ac0f747099b2096470d62b0a9c72f73a",
        "shortHash": "d8bb077",
        "author": "夏坤明",
        "time": "6 months ago",
        "message": "feat: 代码片段编辑器保存快捷键。",
        "additions": 76,
        "deletions": 49
      },
      {
        "hash": "e6fcd80f5fa926b0f033a131d2d5f21a8b505fc2",
        "shortHash": "e6fcd80",
        "author": "夏坤明",
        "time": "6 months ago",
        "message": "docs: 添加项目说明文件",
        "additions": 45,
        "deletions": 0
      },
      {
        "hash": "f976f01b01c3354fb795817e5b663d96d00f062a",
        "shortHash": "f976f01",
        "author": "夏坤明",
        "time": "6 months ago",
        "message": "样式调整",
        "additions": 268,
        "deletions": 206
      }
    ]
  },
  {
    "id": "gistsync-e6bd1f",
    "name": "GistSync",
    "branch": "codex/fix-advanced-sync-item-selection",
    "path": "E:/github/GistSync",
    "remote": "origin",
    "category": "GitHub 工作区",
    "modified": 0,
    "ahead": 1,
    "behind": 0,
    "conflicts": 0,
    "status": "clean",
    "lastScan": "09:59:41",
    "files": [],
    "stagedCount": 0,
    "unstagedCount": 0,
    "scannedAt": "2026/7/1 09:59:41",
    "history": [
      {
        "hash": "62bc4de989f23d50e2dcb634aeb99c077c54ddff",
        "shortHash": "62bc4de",
        "author": "xiakunming",
        "time": "5 days ago",
        "message": "fix(sync): normalize duplicate item ids",
        "additions": 302,
        "deletions": 10
      },
      {
        "hash": "d55eb35ae6e247f1c5dbb19df59a883946fe2ad9",
        "shortHash": "d55eb35",
        "author": "夏坤明",
        "time": "3 weeks ago",
        "message": "feat(profile): 实现配置条目启用/禁用及 LCS 差异渲染",
        "additions": 741,
        "deletions": 244
      },
      {
        "hash": "1ffe4a19a01ecad18f95891ca7d94884bcb45738",
        "shortHash": "1ffe4a1",
        "author": "夏坤明",
        "time": "3 weeks ago",
        "message": "chore(docs): 初始化 CodeStable 工作流骨架和参考文档",
        "additions": 1389,
        "deletions": 314
      },
      {
        "hash": "70ccfd3dd35ee2f7cd9912fbb8b5f7c78d7bba88",
        "shortHash": "70ccfd3",
        "author": "xiakunming",
        "time": "4 weeks ago",
        "message": "chore(config): 更新 .gitignore 和升级前端构建工具链",
        "additions": 78,
        "deletions": 128
      },
      {
        "hash": "efcedd876d99cce7fbd8c397dd4521536c82f275",
        "shortHash": "efcedd8",
        "author": "xiakunming",
        "time": "6 weeks ago",
        "message": "feat(sync): 实现冲突差异预览和启动时快照自动同步",
        "additions": 498,
        "deletions": 49
      }
    ]
  },
  {
    "id": "h5-bl-106613",
    "name": "h5-bl",
    "branch": "master",
    "path": "E:/h5-bl",
    "remote": "origin",
    "category": "本地项目",
    "modified": 0,
    "ahead": 0,
    "behind": 0,
    "conflicts": 0,
    "status": "clean",
    "lastScan": "09:59:41",
    "files": [],
    "stagedCount": 0,
    "unstagedCount": 0,
    "scannedAt": "2026/7/1 09:59:41",
    "history": [
      {
        "hash": "8286039dd21597762c5fc5ca519bd04945ddf3f4",
        "shortHash": "8286039",
        "author": "xiakunming",
        "time": "5 days ago",
        "message": "test: 添加 MockRoute 类型以增强路由对象类型定义",
        "additions": 21,
        "deletions": 3
      },
      {
        "hash": "fedca0ee5af5599210b1fc156ce49a8ff6509c28",
        "shortHash": "fedca0e",
        "author": "xiakunming",
        "time": "5 days ago",
        "message": "test(applyPageAirbridge): 重构模拟路由逻辑并添加反应式路由",
        "additions": 39,
        "deletions": 7
      },
      {
        "hash": "290f5c9c998cb826f40f2e849c222ac2590389ef",
        "shortHash": "290f5c9",
        "author": "xiakunming",
        "time": "5 days ago",
        "message": "feat(baseInfo): 实现步骤导航的哈希路由管理",
        "additions": 189,
        "deletions": 37
      },
      {
        "hash": "3ee2aeb716a84099dbee3cd887810d22432a07e1",
        "shortHash": "3ee2aeb",
        "author": "xiakunming",
        "time": "5 days ago",
        "message": "feat(liveness): 支持高级版活体检测通道",
        "additions": 106,
        "deletions": 29
      },
      {
        "hash": "d8af15d5456e5ced6a0f65f8e1051d412b8526e4",
        "shortHash": "d8af15d",
        "author": "xiakunming",
        "time": "5 days ago",
        "message": "feat(baseinfo): 新增 advanced 活体通道支持，重构活体配置读取逻辑",
        "additions": 106,
        "deletions": 29
      }
    ]
  },
  {
    "id": "h5-bridge-devtools-5484d4",
    "name": "H5-Bridge-DevTools",
    "branch": "master",
    "path": "E:/github/H5-Bridge-DevTools",
    "remote": "origin",
    "category": "GitHub 工作区",
    "modified": 0,
    "ahead": 0,
    "behind": 0,
    "conflicts": 0,
    "status": "clean",
    "lastScan": "09:59:41",
    "files": [],
    "stagedCount": 0,
    "unstagedCount": 0,
    "scannedAt": "2026/7/1 09:59:41",
    "history": [
      {
        "hash": "934f6679dbd36f5154c501e805917621b3979246",
        "shortHash": "934f667",
        "author": "夏坤明",
        "time": "35 hours ago",
        "message": "feat(panel): 实现独立安卓发送容器及 UI 改造",
        "additions": 458,
        "deletions": 104
      },
      {
        "hash": "ad82d96033a8b1e10d11c8d48304f4e911662651",
        "shortHash": "ad82d96",
        "author": "xiakunming",
        "time": "2 days ago",
        "message": "refactor(rules): 提取 ResponseDetailPane 为独立组件并优化样式",
        "additions": 342,
        "deletions": 175
      },
      {
        "hash": "bfba61749578e780df93e911d25d07d1d414ac6b",
        "shortHash": "bfba617",
        "author": "xiakunming",
        "time": "2 days ago",
        "message": "refactor(arch): 重构调试链路，消除对 MV3 Service Worker 常驻的依赖",
        "additions": 660,
        "deletions": 867
      },
      {
        "hash": "380f34a9e89a7457c8c8d99df242a201d9f6de38",
        "shortHash": "380f34a",
        "author": "xiakunming",
        "time": "2 days ago",
        "message": "fix(content): content script 在 service worker 回收后自动重连并回放缓存快照",
        "additions": 449,
        "deletions": 59
      },
      {
        "hash": "96ab0f4db014100d256e46805c7f3a1a6d2f8daa",
        "shortHash": "96ab0f4",
        "author": "夏坤明",
        "time": "2 days ago",
        "message": "feat(panel): 实现面板全局导航历史与鼠标侧键返回",
        "additions": 1356,
        "deletions": 64
      }
    ]
  },
  {
    "id": "h5-code-38fbdc",
    "name": "h5-code",
    "branch": "master",
    "path": "E:/h5-code",
    "remote": "origin",
    "category": "本地项目",
    "modified": 0,
    "ahead": 1,
    "behind": 0,
    "conflicts": 0,
    "status": "clean",
    "lastScan": "09:59:41",
    "files": [],
    "stagedCount": 0,
    "unstagedCount": 0,
    "scannedAt": "2026/7/1 09:59:41",
    "history": [
      {
        "hash": "406d43f3002231426ffe97f399a6a8f590daa7c7",
        "shortHash": "406d43f",
        "author": "xiakunming",
        "time": "14 hours ago",
        "message": "feat(home): 按新Figma设计稿重做02首页全部区块",
        "additions": 853,
        "deletions": 675
      },
      {
        "hash": "79628f22ad8aae09d05d9f9202e9dd5b01bfbcbc",
        "shortHash": "79628f2",
        "author": "xiakunming",
        "time": "18 hours ago",
        "message": "feat(init): 初始化02子项目，包含用户协议、注销、FAQ等完整功能",
        "additions": 11819,
        "deletions": 0
      },
      {
        "hash": "a6c13a285544b85f98accd49d6fcb12d8b87f757",
        "shortHash": "a6c13a2",
        "author": "xiakunming",
        "time": "20 hours ago",
        "message": "refactor(guide): 将 img 发光替换为 CSS 渐变并调整布局",
        "additions": 20,
        "deletions": 28
      },
      {
        "hash": "e20524f6b95f3bef0141978f7300f786e2ed4b03",
        "shortHash": "e20524f",
        "author": "xiakunming",
        "time": "23 hours ago",
        "message": "feat(legal): 将03包法律文件从秘鲁LuckyCrédito迁移至哥伦比亚Alivio+配置",
        "additions": 729,
        "deletions": 417
      },
      {
        "hash": "d5c9bc07b4ba5e5f603718392b58bd376710116f",
        "shortHash": "d5c9bc0",
        "author": "xiakunming",
        "time": "2 days ago",
        "message": "refactor(guide): 按 Figma 新设计重写引导页并清理旧资源",
        "additions": 459,
        "deletions": 333
      }
    ]
  },
  {
    "id": "h5-credit-monorepo-c3dee3",
    "name": "h5-credit-monorepo",
    "branch": "main",
    "path": "E:/h5-credit-monorepo",
    "remote": "origin",
    "category": "本地项目",
    "modified": 0,
    "ahead": 0,
    "behind": 0,
    "conflicts": 0,
    "status": "clean",
    "lastScan": "09:59:41",
    "files": [],
    "stagedCount": 0,
    "unstagedCount": 0,
    "scannedAt": "2026/7/1 09:59:41",
    "history": [
      {
        "hash": "d5839beaf0b356fc4ef2821cd099790158a6daf9",
        "shortHash": "d5839be",
        "author": "xiakunming",
        "time": "17 hours ago",
        "message": "refactor(ui): 使用 SVG 图标替换加载动画 PNG 图片",
        "additions": 22,
        "deletions": 3
      },
      {
        "hash": "56de30d7cbad77dc4e7491d2cdc687600c4b664d",
        "shortHash": "56de30d",
        "author": "xiakunming",
        "time": "2 days ago",
        "message": "feat(native): 实现安卓返回键优先级处理，弹窗优于页面返回",
        "additions": 724,
        "deletions": 2
      },
      {
        "hash": "ac05280dc4afae3dfa97d659e32d19efb3758609",
        "shortHash": "ac05280",
        "author": "xiakunming",
        "time": "2 days ago",
        "message": "feat(ui): 重构跑马灯组件并移除贷款摘要阴影",
        "additions": 135,
        "deletions": 38
      },
      {
        "hash": "844087e6f77070f257f9598aba6bc9e9ac6d8d1f",
        "shortHash": "844087e",
        "author": "xiakunming",
        "time": "2 days ago",
        "message": "docs(dev): 规范单包文档命名规则并建立01包文档索引",
        "additions": 62,
        "deletions": 4
      },
      {
        "hash": "5e59c00e9af61476b4f68bd0daf3dc54cb8ce39b",
        "shortHash": "5e59c00",
        "author": "xiakunming",
        "time": "5 days ago",
        "message": "fix(productApply): 更新 03 包银行卡表单必填提示文案",
        "additions": 76,
        "deletions": 9
      }
    ]
  },
  {
    "id": "node-api-0297d6",
    "name": "node-api",
    "branch": "master",
    "path": "E:/github/node-api",
    "remote": "origin",
    "category": "GitHub 工作区",
    "modified": 0,
    "ahead": 0,
    "behind": 0,
    "conflicts": 0,
    "status": "clean",
    "lastScan": "09:59:41",
    "files": [],
    "stagedCount": 0,
    "unstagedCount": 0,
    "scannedAt": "2026/7/1 09:59:41",
    "history": [
      {
        "hash": "bfb8a367aefbbcc46fbba0f53157058355e636c0",
        "shortHash": "bfb8a36",
        "author": "夏坤明",
        "time": "1 year, 3 months ago",
        "message": "新增rotation属性，允许绘制的图像进行翻转",
        "additions": 92,
        "deletions": 8
      },
      {
        "hash": "6bddb77c30f9897357606be29cecd8ba8665d6c3",
        "shortHash": "6bddb77",
        "author": "夏坤明",
        "time": "1 year, 3 months ago",
        "message": "新增签名画板",
        "additions": 403,
        "deletions": 0
      },
      {
        "hash": "259697bf594c5e0d4eda7b4ce50b51a08e34d57f",
        "shortHash": "259697b",
        "author": "夏坤明",
        "time": "1 year, 3 months ago",
        "message": "遗漏的变更",
        "additions": 2,
        "deletions": 2
      },
      {
        "hash": "2e5e6ec602cb717c960cad6f79a0da85065fb312",
        "shortHash": "2e5e6ec",
        "author": "夏坤明",
        "time": "1 year, 3 months ago",
        "message": "变更组件位置",
        "additions": 3,
        "deletions": 3
      },
      {
        "hash": "a2af584b7ee6492b7714c1ff7d94c17e80caf2f5",
        "shortHash": "a2af584",
        "author": "夏坤明",
        "time": "1 year, 3 months ago",
        "message": "允许侧边栏折叠、添加侧边栏icon",
        "additions": 6993,
        "deletions": 3600
      }
    ]
  },
  {
    "id": "payday-vue-web-e04b24",
    "name": "payday-vue-web",
    "branch": "master",
    "path": "E:/payday-vue-web",
    "remote": "origin",
    "category": "本地项目",
    "modified": 0,
    "ahead": 0,
    "behind": 0,
    "conflicts": 0,
    "status": "clean",
    "lastScan": "09:59:41",
    "files": [],
    "stagedCount": 0,
    "unstagedCount": 0,
    "scannedAt": "2026/7/1 09:59:41",
    "history": [
      {
        "hash": "b0f52939bce81d360f2e0ef983e68b44f4e12bd6",
        "shortHash": "b0f5293",
        "author": "xiakunming",
        "time": "17 hours ago",
        "message": "style(platformCollection): 完善禁用态主按钮的文字颜色样式",
        "additions": 19,
        "deletions": 0
      },
      {
        "hash": "42051104c7eeaf128cb723fd4b7644fb181b5a20",
        "shortHash": "4205110",
        "author": "xiakunming",
        "time": "17 hours ago",
        "message": "fix(platformCollection): 修复搜索按钮区域布局并优化按钮间距",
        "additions": 37,
        "deletions": 3
      },
      {
        "hash": "815e01a84dbc4110b5d09ee93759b9d1db521223",
        "shortHash": "815e01a",
        "author": "xiakunming",
        "time": "20 hours ago",
        "message": "feat(ui): 侧边栏折叠时隐藏Logo标题并优化动画过渡",
        "additions": 180,
        "deletions": 18
      },
      {
        "hash": "2263eff142497c52f591abb0c5777a80f89bbfac",
        "shortHash": "2263eff",
        "author": "xiakunming",
        "time": "21 hours ago",
        "message": "refactor(ui): 移除平台催收主题模块，统一侧边栏与全局样式",
        "additions": 352,
        "deletions": 772
      },
      {
        "hash": "bde59df3b955be2bdecad24acc5c3a408079ec8e",
        "shortHash": "bde59df",
        "author": "xiakunming",
        "time": "24 hours ago",
        "message": "chore(config): 更新 .gitignore 忽略模式",
        "additions": 11,
        "deletions": 4
      }
    ]
  },
  {
    "id": "weekly-d3d38f",
    "name": "weekly",
    "branch": "master",
    "path": "E:/github/weekly",
    "remote": "origin",
    "category": "GitHub 工作区",
    "modified": 0,
    "ahead": 0,
    "behind": 0,
    "conflicts": 0,
    "status": "clean",
    "lastScan": "09:59:41",
    "files": [],
    "stagedCount": 0,
    "unstagedCount": 0,
    "scannedAt": "2026/7/1 09:59:41",
    "history": [
      {
        "hash": "3f058c82dc04b8c34fac622266cf796d6c44dcd6",
        "shortHash": "3f058c8",
        "author": "ruanyf",
        "time": "3 weeks ago",
        "message": "docs: release issue 400",
        "additions": 363,
        "deletions": 0
      },
      {
        "hash": "8d9cf08a359ec45f62a990dfb9c6af765d9e3dff",
        "shortHash": "8d9cf08",
        "author": "ruanyf",
        "time": "4 weeks ago",
        "message": "docs: release issue 399",
        "additions": 365,
        "deletions": 1
      },
      {
        "hash": "f048bd969f0ff42e1cc515545395b6c622463224",
        "shortHash": "f048bd9",
        "author": "Ruan YiFeng",
        "time": "5 weeks ago",
        "message": "Merge pull request #10109 from jeff-fe/patch-2",
        "additions": 2,
        "deletions": 2
      },
      {
        "hash": "475abd37b8eda5e559d53b02e33399da661bdcda",
        "shortHash": "475abd3",
        "author": "Jeff",
        "time": "5 weeks ago",
        "message": "docs(issue-398): fix typo",
        "additions": 2,
        "deletions": 2
      },
      {
        "hash": "741c5c7292153f4d8e7b948f34d658c7cf5c21f6",
        "shortHash": "741c5c7",
        "author": "ruanyf",
        "time": "5 weeks ago",
        "message": "docs: release issue 398",
        "additions": 386,
        "deletions": 0
      }
    ]
  }
];
export const REPO_DETAILS: Record<string, RepoDetail> = {
  "git-monorepo-tools-5b123e": {
    "id": "git-monorepo-tools-5b123e",
    "name": "git-monorepo-tools",
    "branch": "master",
    "path": "E:/github/git-monorepo-tools",
    "remote": "origin",
    "category": "GitHub 工作区",
    "modified": 29,
    "ahead": 0,
    "behind": 0,
    "conflicts": 0,
    "status": "changed",
    "lastScan": "09:59:41",
    "files": [
      {
        "id": ".codestable/goals/2026-06-30-git-manager-ui-clone/functional-acceptance.md::unstaged",
        "status": "A",
        "path": ".codestable/goals/2026-06-30-git-manager-ui-clone/functional-acceptance.md",
        "additions": 48,
        "deletions": 0,
        "size": "1.3 KB",
        "staged": false
      },
      {
        "id": ".codestable/goals/2026-06-30-git-manager-ui-clone/goal.md::unstaged",
        "status": "A",
        "path": ".codestable/goals/2026-06-30-git-manager-ui-clone/goal.md",
        "additions": 44,
        "deletions": 0,
        "size": "1.3 KB",
        "staged": false
      },
      {
        "id": ".codestable/goals/2026-06-30-git-manager-ui-clone/iterations/001-page.png::unstaged",
        "status": "A",
        "path": ".codestable/goals/2026-06-30-git-manager-ui-clone/iterations/001-page.png",
        "additions": 1550,
        "deletions": 0,
        "size": "349.7 KB",
        "staged": false
      },
      {
        "id": ".codestable/goals/2026-06-30-git-manager-ui-clone/iterations/001.md::unstaged",
        "status": "A",
        "path": ".codestable/goals/2026-06-30-git-manager-ui-clone/iterations/001.md",
        "additions": 44,
        "deletions": 0,
        "size": "1.6 KB",
        "staged": false
      },
      {
        "id": ".codestable/goals/2026-06-30-git-manager-ui-clone/iterations/002.md::unstaged",
        "status": "A",
        "path": ".codestable/goals/2026-06-30-git-manager-ui-clone/iterations/002.md",
        "additions": 50,
        "deletions": 0,
        "size": "1.7 KB",
        "staged": false
      },
      {
        "id": ".codestable/goals/2026-06-30-git-manager-ui-clone/state.yaml::unstaged",
        "status": "A",
        "path": ".codestable/goals/2026-06-30-git-manager-ui-clone/state.yaml",
        "additions": 25,
        "deletions": 0,
        "size": "1014 B",
        "staged": false
      },
      {
        "id": "index.html::unstaged",
        "status": "A",
        "path": "index.html",
        "additions": 14,
        "deletions": 0,
        "size": "350 B",
        "staged": false
      },
      {
        "id": "package-lock.json::unstaged",
        "status": "A",
        "path": "package-lock.json",
        "additions": 1917,
        "deletions": 0,
        "size": "61.8 KB",
        "staged": false
      },
      {
        "id": "package.json::unstaged",
        "status": "A",
        "path": "package.json",
        "additions": 26,
        "deletions": 0,
        "size": "601 B",
        "staged": false
      },
      {
        "id": "scripts/sync-real-data.mjs::unstaged",
        "status": "A",
        "path": "scripts/sync-real-data.mjs",
        "additions": 493,
        "deletions": 0,
        "size": "16.3 KB",
        "staged": false
      },
      {
        "id": "src/app/App.tsx::unstaged",
        "status": "A",
        "path": "src/app/App.tsx",
        "additions": 111,
        "deletions": 0,
        "size": "3.4 KB",
        "staged": false
      },
      {
        "id": "src/app/components/ai-commit-panel.tsx::unstaged",
        "status": "A",
        "path": "src/app/components/ai-commit-panel.tsx",
        "additions": 381,
        "deletions": 0,
        "size": "12.3 KB",
        "staged": false
      },
      {
        "id": "src/app/components/common.tsx::unstaged",
        "status": "A",
        "path": "src/app/components/common.tsx",
        "additions": 62,
        "deletions": 0,
        "size": "1.2 KB",
        "staged": false
      },
      {
        "id": "src/app/components/diff-list.tsx::unstaged",
        "status": "A",
        "path": "src/app/components/diff-list.tsx",
        "additions": 352,
        "deletions": 0,
        "size": "12.1 KB",
        "staged": false
      },
      {
        "id": "src/app/components/diff-preview.tsx::unstaged",
        "status": "A",
        "path": "src/app/components/diff-preview.tsx",
        "additions": 173,
        "deletions": 0,
        "size": "6.7 KB",
        "staged": false
      },
      {
        "id": "src/app/components/pull-all-drawer.tsx::unstaged",
        "status": "A",
        "path": "src/app/components/pull-all-drawer.tsx",
        "additions": 180,
        "deletions": 0,
        "size": "7.7 KB",
        "staged": false
      },
      {
        "id": "src/app/components/settings-modal.tsx::unstaged",
        "status": "A",
        "path": "src/app/components/settings-modal.tsx",
        "additions": 497,
        "deletions": 0,
        "size": "16.6 KB",
        "staged": false
      },
      {
        "id": "src/app/components/sidebar.tsx::unstaged",
        "status": "A",
        "path": "src/app/components/sidebar.tsx",
        "additions": 394,
        "deletions": 0,
        "size": "13.1 KB",
        "staged": false
      },
      {
        "id": "src/app/components/workspace.tsx::unstaged",
        "status": "A",
        "path": "src/app/components/workspace.tsx",
        "additions": 393,
        "deletions": 0,
        "size": "15.8 KB",
        "staged": false
      },
      {
        "id": "src/app/data.ts::unstaged",
        "status": "A",
        "path": "src/app/data.ts",
        "additions": 2113,
        "deletions": 0,
        "size": "56.3 KB",
        "staged": false
      },
      {
        "id": "src/app/theme.ts::unstaged",
        "status": "A",
        "path": "src/app/theme.ts",
        "additions": 25,
        "deletions": 0,
        "size": "576 B",
        "staged": false
      },
      {
        "id": "src/app/types.ts::unstaged",
        "status": "A",
        "path": "src/app/types.ts",
        "additions": 100,
        "deletions": 0,
        "size": "1.9 KB",
        "staged": false
      },
      {
        "id": "src/main.tsx::unstaged",
        "status": "A",
        "path": "src/main.tsx",
        "additions": 6,
        "deletions": 0,
        "size": "168 B",
        "staged": false
      },
      {
        "id": "src/styles/fonts.css::unstaged",
        "status": "A",
        "path": "src/styles/fonts.css",
        "additions": 2,
        "deletions": 0,
        "size": "136 B",
        "staged": false
      },
      {
        "id": "src/styles/index.css::unstaged",
        "status": "A",
        "path": "src/styles/index.css",
        "additions": 73,
        "deletions": 0,
        "size": "940 B",
        "staged": false
      },
      {
        "id": "src/vite-env.d.ts::unstaged",
        "status": "A",
        "path": "src/vite-env.d.ts",
        "additions": 2,
        "deletions": 0,
        "size": "38 B",
        "staged": false
      },
      {
        "id": "tsconfig.json::unstaged",
        "status": "A",
        "path": "tsconfig.json",
        "additions": 23,
        "deletions": 0,
        "size": "616 B",
        "staged": false
      },
      {
        "id": "tsconfig.node.json::unstaged",
        "status": "A",
        "path": "tsconfig.node.json",
        "additions": 13,
        "deletions": 0,
        "size": "250 B",
        "staged": false
      },
      {
        "id": "vite.config.ts::unstaged",
        "status": "A",
        "path": "vite.config.ts",
        "additions": 10,
        "deletions": 0,
        "size": "174 B",
        "staged": false
      }
    ],
    "stagedCount": 0,
    "unstagedCount": 29,
    "scannedAt": "2026/7/1 09:59:41",
    "history": [
      {
        "hash": "0237c860ccf31373d664665feda79d7d3d253ba3",
        "shortHash": "0237c86",
        "author": "xiakunming",
        "time": "14 hours ago",
        "message": "init",
        "additions": 9513,
        "deletions": 0
      }
    ]
  },
  "dschat-5182d3": {
    "id": "dschat-5182d3",
    "name": "dsChat",
    "branch": "master",
    "path": "E:/github/dsChat",
    "remote": "origin",
    "category": "GitHub 工作区",
    "modified": 19,
    "ahead": 0,
    "behind": 0,
    "conflicts": 0,
    "status": "changed",
    "lastScan": "09:59:41",
    "files": [
      {
        "id": ".codestable/architecture/ARCHITECTURE.md::unstaged",
        "status": "A",
        "path": ".codestable/architecture/ARCHITECTURE.md",
        "additions": 15,
        "deletions": 0,
        "size": "229 B",
        "staged": false
      },
      {
        "id": ".codestable/attention.md::unstaged",
        "status": "A",
        "path": ".codestable/attention.md",
        "additions": 22,
        "deletions": 0,
        "size": "404 B",
        "staged": false
      },
      {
        "id": ".codestable/compound/.gitkeep::unstaged",
        "status": "A",
        "path": ".codestable/compound/.gitkeep",
        "additions": 2,
        "deletions": 0,
        "size": "1 B",
        "staged": false
      },
      {
        "id": ".codestable/features/2026-05-24-tool-calling/tool-calling-design.md::unstaged",
        "status": "A",
        "path": ".codestable/features/2026-05-24-tool-calling/tool-calling-design.md",
        "additions": 261,
        "deletions": 0,
        "size": "9.2 KB",
        "staged": false
      },
      {
        "id": ".codestable/issues/.gitkeep::unstaged",
        "status": "A",
        "path": ".codestable/issues/.gitkeep",
        "additions": 2,
        "deletions": 0,
        "size": "1 B",
        "staged": false
      },
      {
        "id": ".codestable/reference/code-dimensions.md::unstaged",
        "status": "A",
        "path": ".codestable/reference/code-dimensions.md",
        "additions": 98,
        "deletions": 0,
        "size": "4.8 KB",
        "staged": false
      },
      {
        "id": ".codestable/reference/maintainer-notes.md::unstaged",
        "status": "A",
        "path": ".codestable/reference/maintainer-notes.md",
        "additions": 50,
        "deletions": 0,
        "size": "2.6 KB",
        "staged": false
      },
      {
        "id": ".codestable/reference/requirement-example.md::unstaged",
        "status": "A",
        "path": ".codestable/reference/requirement-example.md",
        "additions": 89,
        "deletions": 0,
        "size": "3.2 KB",
        "staged": false
      },
      {
        "id": ".codestable/reference/shared-conventions.md::unstaged",
        "status": "A",
        "path": ".codestable/reference/shared-conventions.md",
        "additions": 253,
        "deletions": 0,
        "size": "15.1 KB",
        "staged": false
      },
      {
        "id": ".codestable/reference/system-overview.md::unstaged",
        "status": "A",
        "path": ".codestable/reference/system-overview.md",
        "additions": 115,
        "deletions": 0,
        "size": "7.6 KB",
        "staged": false
      },
      {
        "id": ".codestable/reference/tools.md::unstaged",
        "status": "A",
        "path": ".codestable/reference/tools.md",
        "additions": 101,
        "deletions": 0,
        "size": "5.7 KB",
        "staged": false
      },
      {
        "id": ".codestable/requirements/.gitkeep::unstaged",
        "status": "A",
        "path": ".codestable/requirements/.gitkeep",
        "additions": 2,
        "deletions": 0,
        "size": "1 B",
        "staged": false
      },
      {
        "id": ".codestable/roadmap/.gitkeep::unstaged",
        "status": "A",
        "path": ".codestable/roadmap/.gitkeep",
        "additions": 2,
        "deletions": 0,
        "size": "1 B",
        "staged": false
      },
      {
        "id": ".codestable/tools/search-yaml.py::unstaged",
        "status": "A",
        "path": ".codestable/tools/search-yaml.py",
        "additions": 339,
        "deletions": 0,
        "size": "12.7 KB",
        "staged": false
      },
      {
        "id": ".codestable/tools/validate-yaml.py::unstaged",
        "status": "A",
        "path": ".codestable/tools/validate-yaml.py",
        "additions": 316,
        "deletions": 0,
        "size": "11.0 KB",
        "staged": false
      },
      {
        "id": ".gitignore::unstaged",
        "status": "A",
        "path": ".gitignore",
        "additions": 1,
        "deletions": 0,
        "size": "298 B",
        "staged": false
      },
      {
        "id": "docs/tool-calling-architecture.md::unstaged",
        "status": "D",
        "path": "docs/tool-calling-architecture.md",
        "additions": 0,
        "deletions": 260,
        "size": "—",
        "staged": false
      },
      {
        "id": "src/styles/chat-composer-preview.css::unstaged",
        "status": "A",
        "path": "src/styles/chat-composer-preview.css",
        "additions": 39,
        "deletions": 0,
        "size": "716 B",
        "staged": false
      },
      {
        "id": "src/styles/chat-composer.css::unstaged",
        "status": "M",
        "path": "src/styles/chat-composer.css",
        "additions": 158,
        "deletions": 141,
        "size": "6.8 KB",
        "staged": false
      }
    ],
    "stagedCount": 0,
    "unstagedCount": 19,
    "scannedAt": "2026/7/1 09:59:41",
    "history": [
      {
        "hash": "28a22e6968e3901c48cca25b9eee59e1a82b6a61",
        "shortHash": "28a22e6",
        "author": "xiakunming",
        "time": "5 weeks ago",
        "message": "fix(session): restore idle reset on plugin reopen",
        "additions": 163,
        "deletions": 38
      },
      {
        "hash": "a2d943f981c9b5074ae94f5d9a44bd5b2c5fc2fc",
        "shortHash": "a2d943f",
        "author": "夏坤明",
        "time": "6 weeks ago",
        "message": "refactor(ui): 重构代码块复制按钮 DOM 结构并优化高亮降级逻辑",
        "additions": 80,
        "deletions": 31
      },
      {
        "hash": "edea5933a940935cfb84eb196945f5fcb0101aa3",
        "shortHash": "edea593",
        "author": "xiakunming",
        "time": "6 weeks ago",
        "message": "feat(ui): 实现消息复制成功动画及服务商删除确认弹窗",
        "additions": 241,
        "deletions": 31
      },
      {
        "hash": "f726c72097c8a529e4a1af3bbbd6daaccfa8d7d0",
        "shortHash": "f726c72",
        "author": "xiakunming",
        "time": "6 weeks ago",
        "message": "refactor(tools): 移除 OpenAI 原生搜索开关，重构工具调用协议校验",
        "additions": 139,
        "deletions": 74
      },
      {
        "hash": "4bccd4a660b81769dc8f1365515b7b2620cdf3f7",
        "shortHash": "4bccd4a",
        "author": "xiakunming",
        "time": "6 weeks ago",
        "message": "feat(settings): 实现服务商能力可编辑系统",
        "additions": 908,
        "deletions": 216
      }
    ]
  },
  "codestable-155430": {
    "id": "codestable-155430",
    "name": "CodeStable",
    "branch": "main",
    "path": "E:/github/CodeStable",
    "remote": "origin",
    "category": "GitHub 工作区",
    "modified": 6,
    "ahead": 0,
    "behind": 0,
    "conflicts": 0,
    "status": "changed",
    "lastScan": "09:59:41",
    "files": [
      {
        "id": ".codegraph/.gitignore::unstaged",
        "status": "A",
        "path": ".codegraph/.gitignore",
        "additions": 6,
        "deletions": 0,
        "size": "229 B",
        "staged": false
      },
      {
        "id": ".codegraph/codegraph.db::unstaged",
        "status": "A",
        "path": ".codegraph/codegraph.db",
        "additions": 3354,
        "deletions": 0,
        "size": "756.0 KB",
        "staged": false
      },
      {
        "id": ".codegraph/codegraph.db-shm::unstaged",
        "status": "A",
        "path": ".codegraph/codegraph.db-shm",
        "additions": 1,
        "deletions": 0,
        "size": "32.0 KB",
        "staged": false
      },
      {
        "id": ".codegraph/codegraph.db-wal::unstaged",
        "status": "A",
        "path": ".codegraph/codegraph.db-wal",
        "additions": 0,
        "deletions": 0,
        "size": "—",
        "staged": false
      },
      {
        "id": ".codegraph/daemon.log::unstaged",
        "status": "A",
        "path": ".codegraph/daemon.log",
        "additions": 3,
        "deletions": 0,
        "size": "184 B",
        "staged": false
      },
      {
        "id": ".codegraph/daemon.pid::unstaged",
        "status": "A",
        "path": ".codegraph/daemon.pid",
        "additions": 7,
        "deletions": 0,
        "size": "130 B",
        "staged": false
      }
    ],
    "stagedCount": 0,
    "unstagedCount": 6,
    "scannedAt": "2026/7/1 09:59:41",
    "history": [
      {
        "hash": "5377548f4aa7ccfe934b418853b5c28dce293b27",
        "shortHash": "5377548",
        "author": "liuzhengdong",
        "time": "8 weeks ago",
        "message": "feat: Add simphtml.py for enhanced HTML optimization and analysis",
        "additions": 2920,
        "deletions": 0
      },
      {
        "hash": "9216e88d1749830a1d31b6f730798b52f1a4715b",
        "shortHash": "9216e88",
        "author": "liuzhengdong",
        "time": "8 weeks ago",
        "message": "Refactor CodeStable documentation and scripts for improved clarity and structure",
        "additions": 581,
        "deletions": 416
      },
      {
        "hash": "2f44a363407f3858f8c476375c9a7c31f0e93f17",
        "shortHash": "2f44a36",
        "author": "liuzhengdong",
        "time": "9 weeks ago",
        "message": "feat: update case classification and discussion guidelines in cs-brainstorm for improved clarity and structure",
        "additions": 142,
        "deletions": 74
      },
      {
        "hash": "f8c9045adce1ae1ac826068d2034dc62e58d83f1",
        "shortHash": "f8c9045",
        "author": "liuzhengdong",
        "time": "9 weeks ago",
        "message": "feat: refine pre-action guidelines in cs-brainstorm, cs-feat-design, cs-feat-ff, and cs-issue-analyze skills for improved clarity and consistency",
        "additions": 24,
        "deletions": 33
      },
      {
        "hash": "871949be929d3a7e5b5f5b06883d2ae9a817da2a",
        "shortHash": "871949b",
        "author": "liuzhengdong",
        "time": "9 weeks ago",
        "message": "feat: add cs-audit skill and reference templates for system auditing capabilities",
        "additions": 274,
        "deletions": 1
      }
    ]
  },
  "projectnexus-92f7aa": {
    "id": "projectnexus-92f7aa",
    "name": "ProjectNexus",
    "branch": "main",
    "path": "E:/github/ProjectNexus",
    "remote": "origin",
    "category": "GitHub 工作区",
    "modified": 2,
    "ahead": 0,
    "behind": 0,
    "conflicts": 0,
    "status": "changed",
    "lastScan": "09:59:41",
    "files": [
      {
        "id": ".codegraph/.gitignore::unstaged",
        "status": "M",
        "path": ".codegraph/.gitignore",
        "additions": 5,
        "deletions": 16,
        "size": "229 B",
        "staged": false
      },
      {
        "id": "package-lock.json::unstaged",
        "status": "A",
        "path": "package-lock.json",
        "additions": 1,
        "deletions": 0,
        "size": "581.8 KB",
        "staged": false
      }
    ],
    "stagedCount": 0,
    "unstagedCount": 2,
    "scannedAt": "2026/7/1 09:59:41",
    "history": [
      {
        "hash": "1aba22a030e4796b84f380572f12d1127ff09173",
        "shortHash": "1aba22a",
        "author": "xiakunming",
        "time": "13 days ago",
        "message": "fix(domain): IdGenerator 改用 crypto.randomUUID，消除碰撞与弃用 API",
        "additions": 54,
        "deletions": 1
      },
      {
        "hash": "161961c294e9fecd2df9ffa76ea49abc8cfd062c",
        "shortHash": "161961c",
        "author": "xiakunming",
        "time": "13 days ago",
        "message": "fix(sync): 分片拉取在校验和相等但字节数不同时仍拉取",
        "additions": 163,
        "deletions": 1
      },
      {
        "hash": "c462dc5db7508040ea059f9976d1918383670138",
        "shortHash": "c462dc5",
        "author": "xiakunming",
        "time": "13 days ago",
        "message": "fix(sync): 初始化后回填冲突基线，修复新用户首写误报冲突",
        "additions": 65,
        "deletions": 14
      },
      {
        "hash": "6828da9bd5aba390990f33b7493c8aa2ccee4da6",
        "shortHash": "6828da9",
        "author": "xiakunming",
        "time": "13 days ago",
        "message": "docs(audit): 记录核心同步引擎与安全模块审计发现",
        "additions": 408,
        "deletions": 0
      },
      {
        "hash": "4f119692daef110c6ce694c0b518ae5f17c93b60",
        "shortHash": "4f11969",
        "author": "夏坤明",
        "time": "13 days ago",
        "message": "docs(ARCHITECTURE.md): 更新架构文档以准确反映 2026-03 边界重构",
        "additions": 73,
        "deletions": 31
      }
    ]
  },
  "codex-history-clear-786b96": {
    "id": "codex-history-clear-786b96",
    "name": "codex-history-clear",
    "branch": "master",
    "path": "E:/github/codex-history-clear",
    "remote": "origin",
    "category": "GitHub 工作区",
    "modified": 1,
    "ahead": 0,
    "behind": 0,
    "conflicts": 0,
    "status": "changed",
    "lastScan": "09:59:41",
    "files": [
      {
        "id": "frontend/package.json.md5::unstaged",
        "status": "M",
        "path": "frontend/package.json.md5",
        "additions": 1,
        "deletions": 1,
        "size": "32 B",
        "staged": false
      }
    ],
    "stagedCount": 0,
    "unstagedCount": 1,
    "scannedAt": "2026/7/1 09:59:41",
    "history": [
      {
        "hash": "7ec2b0f09c651e0657d81b310653a95625ab130b",
        "shortHash": "7ec2b0f",
        "author": "夏坤明",
        "time": "12 hours ago",
        "message": "feat(discovery): 实现 rollout 元数据富化与扫描过滤",
        "additions": 716,
        "deletions": 14
      },
      {
        "hash": "986df0bb7f47f8b076652d03a92c8360993cd593",
        "shortHash": "986df0b",
        "author": "夏坤明",
        "time": "12 hours ago",
        "message": "feat(planning): 实现重复分组与删除计划功能",
        "additions": 1635,
        "deletions": 220
      },
      {
        "hash": "6c922082be5e9ed3de23dd01af1240dc7d48d2d6",
        "shortHash": "6c92208",
        "author": "xiakunming",
        "time": "14 hours ago",
        "message": "refactor: remove obsolete scan logic",
        "additions": 87,
        "deletions": 692
      },
      {
        "hash": "1e59d85bf091a2a2eb3d2ad42d1cbce930f03693",
        "shortHash": "1e59d85",
        "author": "xiakunming",
        "time": "16 hours ago",
        "message": "refactor: simplify scan workflow ui",
        "additions": 432,
        "deletions": 288
      },
      {
        "hash": "e91acf29cd08b9cc0c379c923f2dafe3e4979826",
        "shortHash": "e91acf2",
        "author": "xiakunming",
        "time": "16 hours ago",
        "message": "docs: approve reviewed feature designs",
        "additions": 5,
        "deletions": 5
      }
    ]
  },
  "fusi-tools-6e0ef6": {
    "id": "fusi-tools-6e0ef6",
    "name": "fusi-tools",
    "branch": "master",
    "path": "E:/github/fusi-tools",
    "remote": "origin",
    "category": "GitHub 工作区",
    "modified": 1,
    "ahead": 0,
    "behind": 0,
    "conflicts": 0,
    "status": "changed",
    "lastScan": "09:59:41",
    "files": [
      {
        "id": ".codestable/features/.gitkeep::unstaged",
        "status": "A",
        "path": ".codestable/features/.gitkeep",
        "additions": 2,
        "deletions": 0,
        "size": "2 B",
        "staged": false
      }
    ],
    "stagedCount": 0,
    "unstagedCount": 1,
    "scannedAt": "2026/7/1 09:59:41",
    "history": [
      {
        "hash": "eacfb5559395198e45837d4987aad9ee93490864",
        "shortHash": "eacfb55",
        "author": "xiakunming",
        "time": "6 days ago",
        "message": "fix(resourceManager): auto-dismiss file copy notification",
        "additions": 7,
        "deletions": 1
      },
      {
        "hash": "b6c368749fca65f15c63561d6b6bb1635dd3616c",
        "shortHash": "b6c3687",
        "author": "夏坤明",
        "time": "2 weeks ago",
        "message": "feat(docs): 创建 CodeStable 项目管理体系",
        "additions": 1488,
        "deletions": 255
      },
      {
        "hash": "e64f8082e464b5f1acdfc5b1d76af02f0993f28e",
        "shortHash": "e64f808",
        "author": "xixifu",
        "time": "8 weeks ago",
        "message": "config: 将所有模块的 activationEvents 合并为 onStartupFinished",
        "additions": 135,
        "deletions": 171
      },
      {
        "hash": "acc79b233d1773f78170a94a98259b6306cf91d3",
        "shortHash": "acc79b2",
        "author": "xixifu",
        "time": "9 weeks ago",
        "message": "fix(aiCommit): update DeepSeek v4 model mapping",
        "additions": 161,
        "deletions": 27
      },
      {
        "hash": "8075b68f3f4bdea54161cd765199f65bf54b766e",
        "shortHash": "8075b68",
        "author": "xixifu",
        "time": "3 months ago",
        "message": "refactor(ui): silence instant success notifications",
        "additions": 94,
        "deletions": 26
      }
    ]
  },
  "logcat-6d4a4e": {
    "id": "logcat-6d4a4e",
    "name": "logcat",
    "branch": "master",
    "path": "E:/github/logcat",
    "remote": "origin",
    "category": "GitHub 工作区",
    "modified": 1,
    "ahead": 0,
    "behind": 0,
    "conflicts": 0,
    "status": "changed",
    "lastScan": "09:59:41",
    "files": [
      {
        "id": "frontend/package.json.md5::unstaged",
        "status": "M",
        "path": "frontend/package.json.md5",
        "additions": 1,
        "deletions": 1,
        "size": "32 B",
        "staged": false
      }
    ],
    "stagedCount": 0,
    "unstagedCount": 1,
    "scannedAt": "2026/7/1 09:59:41",
    "history": [
      {
        "hash": "805f27aa868950e0de46742374fc648cb95577d1",
        "shortHash": "805f27a",
        "author": "夏坤明",
        "time": "12 days ago",
        "message": "slim focused selection snapshot payload",
        "additions": 88,
        "deletions": 16
      },
      {
        "hash": "8b7f091fd9ec699932fd29699757dfd1ea4973cb",
        "shortHash": "8b7f091",
        "author": "夏坤明",
        "time": "12 days ago",
        "message": "speed up visible selection lookups",
        "additions": 120,
        "deletions": 8
      },
      {
        "hash": "b9c77b854408967220f01a82fe39238f58cc7d92",
        "shortHash": "b9c77b8",
        "author": "夏坤明",
        "time": "12 days ago",
        "message": "speed up focused snapshot lookup",
        "additions": 67,
        "deletions": 6
      },
      {
        "hash": "aff962842db75af468b3b0dde46a26da2b553c24",
        "shortHash": "aff9628",
        "author": "夏坤明",
        "time": "12 days ago",
        "message": "remove rebuild selection scratch alloc",
        "additions": 61,
        "deletions": 1
      },
      {
        "hash": "ec01918237feee0b6bae5af4b2d3bcbc366d3fd8",
        "shortHash": "ec01918",
        "author": "夏坤明",
        "time": "12 days ago",
        "message": "speed up selection patch apply path",
        "additions": 327,
        "deletions": 14
      }
    ]
  },
  "codepocket-71cb72": {
    "id": "codepocket-71cb72",
    "name": "CodePocket",
    "branch": "main",
    "path": "E:/github/CodePocket",
    "remote": "origin",
    "category": "GitHub 工作区",
    "modified": 0,
    "ahead": 0,
    "behind": 0,
    "conflicts": 0,
    "status": "clean",
    "lastScan": "09:59:41",
    "files": [],
    "stagedCount": 0,
    "unstagedCount": 0,
    "scannedAt": "2026/7/1 09:59:41",
    "history": [
      {
        "hash": "53afd9355395b216fdb3552919b9dc20500d24d1",
        "shortHash": "53afd93",
        "author": "xixifu",
        "time": "6 months ago",
        "message": "feat(manifest): 添加多尺寸图标并格式化清单",
        "additions": 19,
        "deletions": 6
      },
      {
        "hash": "bf0d2d21e6bb520bf995580f3cef2b09081a8f3d",
        "shortHash": "bf0d2d2",
        "author": "夏坤明",
        "time": "6 months ago",
        "message": "feat: 设置变更，允许保存后自动运行",
        "additions": 219,
        "deletions": 152
      },
      {
        "hash": "d8bb0773ac0f747099b2096470d62b0a9c72f73a",
        "shortHash": "d8bb077",
        "author": "夏坤明",
        "time": "6 months ago",
        "message": "feat: 代码片段编辑器保存快捷键。",
        "additions": 76,
        "deletions": 49
      },
      {
        "hash": "e6fcd80f5fa926b0f033a131d2d5f21a8b505fc2",
        "shortHash": "e6fcd80",
        "author": "夏坤明",
        "time": "6 months ago",
        "message": "docs: 添加项目说明文件",
        "additions": 45,
        "deletions": 0
      },
      {
        "hash": "f976f01b01c3354fb795817e5b663d96d00f062a",
        "shortHash": "f976f01",
        "author": "夏坤明",
        "time": "6 months ago",
        "message": "样式调整",
        "additions": 268,
        "deletions": 206
      }
    ]
  },
  "gistsync-e6bd1f": {
    "id": "gistsync-e6bd1f",
    "name": "GistSync",
    "branch": "codex/fix-advanced-sync-item-selection",
    "path": "E:/github/GistSync",
    "remote": "origin",
    "category": "GitHub 工作区",
    "modified": 0,
    "ahead": 1,
    "behind": 0,
    "conflicts": 0,
    "status": "clean",
    "lastScan": "09:59:41",
    "files": [],
    "stagedCount": 0,
    "unstagedCount": 0,
    "scannedAt": "2026/7/1 09:59:41",
    "history": [
      {
        "hash": "62bc4de989f23d50e2dcb634aeb99c077c54ddff",
        "shortHash": "62bc4de",
        "author": "xiakunming",
        "time": "5 days ago",
        "message": "fix(sync): normalize duplicate item ids",
        "additions": 302,
        "deletions": 10
      },
      {
        "hash": "d55eb35ae6e247f1c5dbb19df59a883946fe2ad9",
        "shortHash": "d55eb35",
        "author": "夏坤明",
        "time": "3 weeks ago",
        "message": "feat(profile): 实现配置条目启用/禁用及 LCS 差异渲染",
        "additions": 741,
        "deletions": 244
      },
      {
        "hash": "1ffe4a19a01ecad18f95891ca7d94884bcb45738",
        "shortHash": "1ffe4a1",
        "author": "夏坤明",
        "time": "3 weeks ago",
        "message": "chore(docs): 初始化 CodeStable 工作流骨架和参考文档",
        "additions": 1389,
        "deletions": 314
      },
      {
        "hash": "70ccfd3dd35ee2f7cd9912fbb8b5f7c78d7bba88",
        "shortHash": "70ccfd3",
        "author": "xiakunming",
        "time": "4 weeks ago",
        "message": "chore(config): 更新 .gitignore 和升级前端构建工具链",
        "additions": 78,
        "deletions": 128
      },
      {
        "hash": "efcedd876d99cce7fbd8c397dd4521536c82f275",
        "shortHash": "efcedd8",
        "author": "xiakunming",
        "time": "6 weeks ago",
        "message": "feat(sync): 实现冲突差异预览和启动时快照自动同步",
        "additions": 498,
        "deletions": 49
      }
    ]
  },
  "h5-bl-106613": {
    "id": "h5-bl-106613",
    "name": "h5-bl",
    "branch": "master",
    "path": "E:/h5-bl",
    "remote": "origin",
    "category": "本地项目",
    "modified": 0,
    "ahead": 0,
    "behind": 0,
    "conflicts": 0,
    "status": "clean",
    "lastScan": "09:59:41",
    "files": [],
    "stagedCount": 0,
    "unstagedCount": 0,
    "scannedAt": "2026/7/1 09:59:41",
    "history": [
      {
        "hash": "8286039dd21597762c5fc5ca519bd04945ddf3f4",
        "shortHash": "8286039",
        "author": "xiakunming",
        "time": "5 days ago",
        "message": "test: 添加 MockRoute 类型以增强路由对象类型定义",
        "additions": 21,
        "deletions": 3
      },
      {
        "hash": "fedca0ee5af5599210b1fc156ce49a8ff6509c28",
        "shortHash": "fedca0e",
        "author": "xiakunming",
        "time": "5 days ago",
        "message": "test(applyPageAirbridge): 重构模拟路由逻辑并添加反应式路由",
        "additions": 39,
        "deletions": 7
      },
      {
        "hash": "290f5c9c998cb826f40f2e849c222ac2590389ef",
        "shortHash": "290f5c9",
        "author": "xiakunming",
        "time": "5 days ago",
        "message": "feat(baseInfo): 实现步骤导航的哈希路由管理",
        "additions": 189,
        "deletions": 37
      },
      {
        "hash": "3ee2aeb716a84099dbee3cd887810d22432a07e1",
        "shortHash": "3ee2aeb",
        "author": "xiakunming",
        "time": "5 days ago",
        "message": "feat(liveness): 支持高级版活体检测通道",
        "additions": 106,
        "deletions": 29
      },
      {
        "hash": "d8af15d5456e5ced6a0f65f8e1051d412b8526e4",
        "shortHash": "d8af15d",
        "author": "xiakunming",
        "time": "5 days ago",
        "message": "feat(baseinfo): 新增 advanced 活体通道支持，重构活体配置读取逻辑",
        "additions": 106,
        "deletions": 29
      }
    ]
  },
  "h5-bridge-devtools-5484d4": {
    "id": "h5-bridge-devtools-5484d4",
    "name": "H5-Bridge-DevTools",
    "branch": "master",
    "path": "E:/github/H5-Bridge-DevTools",
    "remote": "origin",
    "category": "GitHub 工作区",
    "modified": 0,
    "ahead": 0,
    "behind": 0,
    "conflicts": 0,
    "status": "clean",
    "lastScan": "09:59:41",
    "files": [],
    "stagedCount": 0,
    "unstagedCount": 0,
    "scannedAt": "2026/7/1 09:59:41",
    "history": [
      {
        "hash": "934f6679dbd36f5154c501e805917621b3979246",
        "shortHash": "934f667",
        "author": "夏坤明",
        "time": "35 hours ago",
        "message": "feat(panel): 实现独立安卓发送容器及 UI 改造",
        "additions": 458,
        "deletions": 104
      },
      {
        "hash": "ad82d96033a8b1e10d11c8d48304f4e911662651",
        "shortHash": "ad82d96",
        "author": "xiakunming",
        "time": "2 days ago",
        "message": "refactor(rules): 提取 ResponseDetailPane 为独立组件并优化样式",
        "additions": 342,
        "deletions": 175
      },
      {
        "hash": "bfba61749578e780df93e911d25d07d1d414ac6b",
        "shortHash": "bfba617",
        "author": "xiakunming",
        "time": "2 days ago",
        "message": "refactor(arch): 重构调试链路，消除对 MV3 Service Worker 常驻的依赖",
        "additions": 660,
        "deletions": 867
      },
      {
        "hash": "380f34a9e89a7457c8c8d99df242a201d9f6de38",
        "shortHash": "380f34a",
        "author": "xiakunming",
        "time": "2 days ago",
        "message": "fix(content): content script 在 service worker 回收后自动重连并回放缓存快照",
        "additions": 449,
        "deletions": 59
      },
      {
        "hash": "96ab0f4db014100d256e46805c7f3a1a6d2f8daa",
        "shortHash": "96ab0f4",
        "author": "夏坤明",
        "time": "2 days ago",
        "message": "feat(panel): 实现面板全局导航历史与鼠标侧键返回",
        "additions": 1356,
        "deletions": 64
      }
    ]
  },
  "h5-code-38fbdc": {
    "id": "h5-code-38fbdc",
    "name": "h5-code",
    "branch": "master",
    "path": "E:/h5-code",
    "remote": "origin",
    "category": "本地项目",
    "modified": 0,
    "ahead": 1,
    "behind": 0,
    "conflicts": 0,
    "status": "clean",
    "lastScan": "09:59:41",
    "files": [],
    "stagedCount": 0,
    "unstagedCount": 0,
    "scannedAt": "2026/7/1 09:59:41",
    "history": [
      {
        "hash": "406d43f3002231426ffe97f399a6a8f590daa7c7",
        "shortHash": "406d43f",
        "author": "xiakunming",
        "time": "14 hours ago",
        "message": "feat(home): 按新Figma设计稿重做02首页全部区块",
        "additions": 853,
        "deletions": 675
      },
      {
        "hash": "79628f22ad8aae09d05d9f9202e9dd5b01bfbcbc",
        "shortHash": "79628f2",
        "author": "xiakunming",
        "time": "18 hours ago",
        "message": "feat(init): 初始化02子项目，包含用户协议、注销、FAQ等完整功能",
        "additions": 11819,
        "deletions": 0
      },
      {
        "hash": "a6c13a285544b85f98accd49d6fcb12d8b87f757",
        "shortHash": "a6c13a2",
        "author": "xiakunming",
        "time": "20 hours ago",
        "message": "refactor(guide): 将 img 发光替换为 CSS 渐变并调整布局",
        "additions": 20,
        "deletions": 28
      },
      {
        "hash": "e20524f6b95f3bef0141978f7300f786e2ed4b03",
        "shortHash": "e20524f",
        "author": "xiakunming",
        "time": "23 hours ago",
        "message": "feat(legal): 将03包法律文件从秘鲁LuckyCrédito迁移至哥伦比亚Alivio+配置",
        "additions": 729,
        "deletions": 417
      },
      {
        "hash": "d5c9bc07b4ba5e5f603718392b58bd376710116f",
        "shortHash": "d5c9bc0",
        "author": "xiakunming",
        "time": "2 days ago",
        "message": "refactor(guide): 按 Figma 新设计重写引导页并清理旧资源",
        "additions": 459,
        "deletions": 333
      }
    ]
  },
  "h5-credit-monorepo-c3dee3": {
    "id": "h5-credit-monorepo-c3dee3",
    "name": "h5-credit-monorepo",
    "branch": "main",
    "path": "E:/h5-credit-monorepo",
    "remote": "origin",
    "category": "本地项目",
    "modified": 0,
    "ahead": 0,
    "behind": 0,
    "conflicts": 0,
    "status": "clean",
    "lastScan": "09:59:41",
    "files": [],
    "stagedCount": 0,
    "unstagedCount": 0,
    "scannedAt": "2026/7/1 09:59:41",
    "history": [
      {
        "hash": "d5839beaf0b356fc4ef2821cd099790158a6daf9",
        "shortHash": "d5839be",
        "author": "xiakunming",
        "time": "17 hours ago",
        "message": "refactor(ui): 使用 SVG 图标替换加载动画 PNG 图片",
        "additions": 22,
        "deletions": 3
      },
      {
        "hash": "56de30d7cbad77dc4e7491d2cdc687600c4b664d",
        "shortHash": "56de30d",
        "author": "xiakunming",
        "time": "2 days ago",
        "message": "feat(native): 实现安卓返回键优先级处理，弹窗优于页面返回",
        "additions": 724,
        "deletions": 2
      },
      {
        "hash": "ac05280dc4afae3dfa97d659e32d19efb3758609",
        "shortHash": "ac05280",
        "author": "xiakunming",
        "time": "2 days ago",
        "message": "feat(ui): 重构跑马灯组件并移除贷款摘要阴影",
        "additions": 135,
        "deletions": 38
      },
      {
        "hash": "844087e6f77070f257f9598aba6bc9e9ac6d8d1f",
        "shortHash": "844087e",
        "author": "xiakunming",
        "time": "2 days ago",
        "message": "docs(dev): 规范单包文档命名规则并建立01包文档索引",
        "additions": 62,
        "deletions": 4
      },
      {
        "hash": "5e59c00e9af61476b4f68bd0daf3dc54cb8ce39b",
        "shortHash": "5e59c00",
        "author": "xiakunming",
        "time": "5 days ago",
        "message": "fix(productApply): 更新 03 包银行卡表单必填提示文案",
        "additions": 76,
        "deletions": 9
      }
    ]
  },
  "node-api-0297d6": {
    "id": "node-api-0297d6",
    "name": "node-api",
    "branch": "master",
    "path": "E:/github/node-api",
    "remote": "origin",
    "category": "GitHub 工作区",
    "modified": 0,
    "ahead": 0,
    "behind": 0,
    "conflicts": 0,
    "status": "clean",
    "lastScan": "09:59:41",
    "files": [],
    "stagedCount": 0,
    "unstagedCount": 0,
    "scannedAt": "2026/7/1 09:59:41",
    "history": [
      {
        "hash": "bfb8a367aefbbcc46fbba0f53157058355e636c0",
        "shortHash": "bfb8a36",
        "author": "夏坤明",
        "time": "1 year, 3 months ago",
        "message": "新增rotation属性，允许绘制的图像进行翻转",
        "additions": 92,
        "deletions": 8
      },
      {
        "hash": "6bddb77c30f9897357606be29cecd8ba8665d6c3",
        "shortHash": "6bddb77",
        "author": "夏坤明",
        "time": "1 year, 3 months ago",
        "message": "新增签名画板",
        "additions": 403,
        "deletions": 0
      },
      {
        "hash": "259697bf594c5e0d4eda7b4ce50b51a08e34d57f",
        "shortHash": "259697b",
        "author": "夏坤明",
        "time": "1 year, 3 months ago",
        "message": "遗漏的变更",
        "additions": 2,
        "deletions": 2
      },
      {
        "hash": "2e5e6ec602cb717c960cad6f79a0da85065fb312",
        "shortHash": "2e5e6ec",
        "author": "夏坤明",
        "time": "1 year, 3 months ago",
        "message": "变更组件位置",
        "additions": 3,
        "deletions": 3
      },
      {
        "hash": "a2af584b7ee6492b7714c1ff7d94c17e80caf2f5",
        "shortHash": "a2af584",
        "author": "夏坤明",
        "time": "1 year, 3 months ago",
        "message": "允许侧边栏折叠、添加侧边栏icon",
        "additions": 6993,
        "deletions": 3600
      }
    ]
  },
  "payday-vue-web-e04b24": {
    "id": "payday-vue-web-e04b24",
    "name": "payday-vue-web",
    "branch": "master",
    "path": "E:/payday-vue-web",
    "remote": "origin",
    "category": "本地项目",
    "modified": 0,
    "ahead": 0,
    "behind": 0,
    "conflicts": 0,
    "status": "clean",
    "lastScan": "09:59:41",
    "files": [],
    "stagedCount": 0,
    "unstagedCount": 0,
    "scannedAt": "2026/7/1 09:59:41",
    "history": [
      {
        "hash": "b0f52939bce81d360f2e0ef983e68b44f4e12bd6",
        "shortHash": "b0f5293",
        "author": "xiakunming",
        "time": "17 hours ago",
        "message": "style(platformCollection): 完善禁用态主按钮的文字颜色样式",
        "additions": 19,
        "deletions": 0
      },
      {
        "hash": "42051104c7eeaf128cb723fd4b7644fb181b5a20",
        "shortHash": "4205110",
        "author": "xiakunming",
        "time": "17 hours ago",
        "message": "fix(platformCollection): 修复搜索按钮区域布局并优化按钮间距",
        "additions": 37,
        "deletions": 3
      },
      {
        "hash": "815e01a84dbc4110b5d09ee93759b9d1db521223",
        "shortHash": "815e01a",
        "author": "xiakunming",
        "time": "20 hours ago",
        "message": "feat(ui): 侧边栏折叠时隐藏Logo标题并优化动画过渡",
        "additions": 180,
        "deletions": 18
      },
      {
        "hash": "2263eff142497c52f591abb0c5777a80f89bbfac",
        "shortHash": "2263eff",
        "author": "xiakunming",
        "time": "21 hours ago",
        "message": "refactor(ui): 移除平台催收主题模块，统一侧边栏与全局样式",
        "additions": 352,
        "deletions": 772
      },
      {
        "hash": "bde59df3b955be2bdecad24acc5c3a408079ec8e",
        "shortHash": "bde59df",
        "author": "xiakunming",
        "time": "24 hours ago",
        "message": "chore(config): 更新 .gitignore 忽略模式",
        "additions": 11,
        "deletions": 4
      }
    ]
  },
  "weekly-d3d38f": {
    "id": "weekly-d3d38f",
    "name": "weekly",
    "branch": "master",
    "path": "E:/github/weekly",
    "remote": "origin",
    "category": "GitHub 工作区",
    "modified": 0,
    "ahead": 0,
    "behind": 0,
    "conflicts": 0,
    "status": "clean",
    "lastScan": "09:59:41",
    "files": [],
    "stagedCount": 0,
    "unstagedCount": 0,
    "scannedAt": "2026/7/1 09:59:41",
    "history": [
      {
        "hash": "3f058c82dc04b8c34fac622266cf796d6c44dcd6",
        "shortHash": "3f058c8",
        "author": "ruanyf",
        "time": "3 weeks ago",
        "message": "docs: release issue 400",
        "additions": 363,
        "deletions": 0
      },
      {
        "hash": "8d9cf08a359ec45f62a990dfb9c6af765d9e3dff",
        "shortHash": "8d9cf08",
        "author": "ruanyf",
        "time": "4 weeks ago",
        "message": "docs: release issue 399",
        "additions": 365,
        "deletions": 1
      },
      {
        "hash": "f048bd969f0ff42e1cc515545395b6c622463224",
        "shortHash": "f048bd9",
        "author": "Ruan YiFeng",
        "time": "5 weeks ago",
        "message": "Merge pull request #10109 from jeff-fe/patch-2",
        "additions": 2,
        "deletions": 2
      },
      {
        "hash": "475abd37b8eda5e559d53b02e33399da661bdcda",
        "shortHash": "475abd3",
        "author": "Jeff",
        "time": "5 weeks ago",
        "message": "docs(issue-398): fix typo",
        "additions": 2,
        "deletions": 2
      },
      {
        "hash": "741c5c7292153f4d8e7b948f34d658c7cf5c21f6",
        "shortHash": "741c5c7",
        "author": "ruanyf",
        "time": "5 weeks ago",
        "message": "docs: release issue 398",
        "additions": 386,
        "deletions": 0
      }
    ]
  }
};
export const SELECTED_REPO_ID = "git-monorepo-tools-5b123e";
export const FILE_CHANGES = REPO_DETAILS[SELECTED_REPO_ID]?.files ?? [];
export const PULL_RESULTS: PullResult[] = [
  {
    "id": "git-monorepo-tools-5b123e",
    "name": "git-monorepo-tools",
    "path": "E:/github/git-monorepo-tools",
    "result": "skipped",
    "detail": "跳过：存在本地未提交改动"
  },
  {
    "id": "dschat-5182d3",
    "name": "dsChat",
    "path": "E:/github/dsChat",
    "result": "skipped",
    "detail": "跳过：存在本地未提交改动"
  },
  {
    "id": "codestable-155430",
    "name": "CodeStable",
    "path": "E:/github/CodeStable",
    "result": "skipped",
    "detail": "跳过：存在本地未提交改动"
  },
  {
    "id": "projectnexus-92f7aa",
    "name": "ProjectNexus",
    "path": "E:/github/ProjectNexus",
    "result": "skipped",
    "detail": "跳过：存在本地未提交改动"
  },
  {
    "id": "codex-history-clear-786b96",
    "name": "codex-history-clear",
    "path": "E:/github/codex-history-clear",
    "result": "skipped",
    "detail": "跳过：存在本地未提交改动"
  },
  {
    "id": "fusi-tools-6e0ef6",
    "name": "fusi-tools",
    "path": "E:/github/fusi-tools",
    "result": "skipped",
    "detail": "跳过：存在本地未提交改动"
  },
  {
    "id": "logcat-6d4a4e",
    "name": "logcat",
    "path": "E:/github/logcat",
    "result": "skipped",
    "detail": "跳过：存在本地未提交改动"
  },
  {
    "id": "codepocket-71cb72",
    "name": "CodePocket",
    "path": "E:/github/CodePocket",
    "result": "uptodate",
    "detail": "工作区干净，已与远端同步"
  },
  {
    "id": "gistsync-e6bd1f",
    "name": "GistSync",
    "path": "E:/github/GistSync",
    "result": "uptodate",
    "detail": "本地领先远端 1 个提交",
    "commits": 1
  },
  {
    "id": "h5-bl-106613",
    "name": "h5-bl",
    "path": "E:/h5-bl",
    "result": "uptodate",
    "detail": "工作区干净，已与远端同步"
  },
  {
    "id": "h5-bridge-devtools-5484d4",
    "name": "H5-Bridge-DevTools",
    "path": "E:/github/H5-Bridge-DevTools",
    "result": "uptodate",
    "detail": "工作区干净，已与远端同步"
  },
  {
    "id": "h5-code-38fbdc",
    "name": "h5-code",
    "path": "E:/h5-code",
    "result": "uptodate",
    "detail": "本地领先远端 1 个提交",
    "commits": 1
  },
  {
    "id": "h5-credit-monorepo-c3dee3",
    "name": "h5-credit-monorepo",
    "path": "E:/h5-credit-monorepo",
    "result": "uptodate",
    "detail": "工作区干净，已与远端同步"
  },
  {
    "id": "node-api-0297d6",
    "name": "node-api",
    "path": "E:/github/node-api",
    "result": "uptodate",
    "detail": "工作区干净，已与远端同步"
  },
  {
    "id": "payday-vue-web-e04b24",
    "name": "payday-vue-web",
    "path": "E:/payday-vue-web",
    "result": "uptodate",
    "detail": "工作区干净，已与远端同步"
  },
  {
    "id": "weekly-d3d38f",
    "name": "weekly",
    "path": "E:/github/weekly",
    "result": "uptodate",
    "detail": "工作区干净，已与远端同步"
  }
];
export const DIFF_LINES: DiffLine[] = [
  {
    "type": "hunk",
    "content": "@@ -0,0 +1,48 @@"
  },
  {
    "type": "added",
    "content": "+---"
  },
  {
    "type": "added",
    "content": "+doc_type: functional-acceptance"
  },
  {
    "type": "added",
    "content": "+goal: \"git-manager-ui-clone\""
  },
  {
    "type": "added",
    "content": "+status: pass"
  },
  {
    "type": "added",
    "content": "+reviewer: \"独立 Task agent\""
  },
  {
    "type": "added",
    "content": "+updated_at: \"2026-06-30\""
  },
  {
    "type": "added",
    "content": "+---"
  },
  {
    "type": "added",
    "content": "+"
  },
  {
    "type": "added",
    "content": "+# 功能验收"
  },
  {
    "type": "added",
    "content": "+"
  },
  {
    "type": "added",
    "content": "+## Reviewer"
  },
  {
    "type": "added",
    "content": "+"
  },
  {
    "type": "added",
    "content": "+独立 Task agent"
  },
  {
    "type": "added",
    "content": "+"
  },
  {
    "type": "added",
    "content": "+## Scope"
  },
  {
    "type": "added",
    "content": "+"
  },
  {
    "type": "added",
    "content": "+`.codestable/goals/2026-06-30-git-manager-ui-clone/goal.md` 的 UI 复刻验收，只读。"
  },
  {
    "type": "added",
    "content": "+"
  },
  {
    "type": "added",
    "content": "+## Checked Acceptance Criteria"
  },
  {
    "type": "added",
    "content": "+"
  },
  {
    "type": "added",
    "content": "+- 应用可构建并启动。"
  },
  {
    "type": "added",
    "content": "+- 页面主结构包含顶部栏、左侧仓库栏、右侧工作区、Pull All 抽屉、Settings 弹窗。"
  },
  {
    "type": "added",
    "content": "+- 所有交互仅依赖 mock 数据，没有真实 Git/后端调用。"
  },
  {
    "type": "added",
    "content": "+- 视觉和结构与 `E:\\其他\\figma-ui` 的信息架构一致。"
  },
  {
    "type": "added",
    "content": "+"
  },
  {
    "type": "added",
    "content": "+## Functional Evidence"
  },
  {
    "type": "added",
    "content": "+"
  },
  {
    "type": "added",
    "content": "+- `npm run build` 成功。"
  },
  {
    "type": "added",
    "content": "+- `http://127.0.0.1:4173/` 返回 200。"
  },
  {
    "type": "added",
    "content": "+- 黑盒检查可见 `VibeGit Desk` 顶栏、`credit-monorepo` 仓库、`Pull All` 按钮、`Settings` 按钮。"
  },
  {
    "type": "added",
    "content": "+- 点击 `Settings` 后可见 `Settings` 模态层，且 `AI Commit` / `Save Changes` 可见。"
  },
  {
    "type": "added",
    "content": "+- 点击 `Pull All` 后可见 `Pull All Results` 抽屉，且 `Done` 可见。"
  },
  {
    "type": "added",
    "content": "+- 截图已生成：`.codestable/goals/2026-06-30-git-manager-ui-clone/iterations/001-page.png`。"
  },
  {
    "type": "added",
    "content": "+- 源码仅依赖 mock 数据与本地状态，未见真实 Git/后端调用链。"
  },
  {
    "type": "added",
    "content": "+"
  },
  {
    "type": "added",
    "content": "+## Verdict"
  },
  {
    "type": "added",
    "content": "+"
  },
  {
    "type": "added",
    "content": "+pass"
  },
  {
    "type": "added",
    "content": "+"
  },
  {
    "type": "added",
    "content": "+## Residual Risks"
  },
  {
    "type": "added",
    "content": "+"
  },
  {
    "type": "added",
    "content": "+- 未做真实网络层抓包，但源码未见真实请求入口，风险较低。"
  },
  {
    "type": "added",
    "content": "+- 若后续页面结构再改动，需要重新验收。"
  },
  {
    "type": "added",
    "content": "+"
  },
  {
    "type": "added",
    "content": "+## Follow-up"
  },
  {
    "type": "added",
    "content": "+"
  },
  {
    "type": "added",
    "content": "+无。"
  },
  {
    "type": "added",
    "content": "+"
  }
];
export const COMMIT_CANDIDATES: Record<string, CommitCandidate[]> = {
  "git-monorepo-tools-5b123e": [],
  "dschat-5182d3": [],
  "codestable-155430": [],
  "projectnexus-92f7aa": [],
  "codex-history-clear-786b96": [],
  "fusi-tools-6e0ef6": [],
  "logcat-6d4a4e": [],
  "codepocket-71cb72": [],
  "gistsync-e6bd1f": [],
  "h5-bl-106613": [],
  "h5-bridge-devtools-5484d4": [],
  "h5-code-38fbdc": [],
  "h5-credit-monorepo-c3dee3": [],
  "node-api-0297d6": [],
  "payday-vue-web-e04b24": [],
  "weekly-d3d38f": []
};
