// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {snapshot} from '../models';

export function GenerateCommitMessage(arg1:string,arg2:snapshot.Request,arg3:snapshot.AICommitSettings):Promise<string>;

export function GetRepoLog(arg1:string,arg2:snapshot.Request):Promise<snapshot.RepoLog>;

export function GetSnapshot(arg1:snapshot.Request):Promise<snapshot.AppSnapshot>;

export function MutateRepo(arg1:string,arg2:string,arg3:snapshot.Request,arg4:snapshot.RepoActionRequest):Promise<snapshot.AppSnapshot>;

export function OpenConflicts(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenTerminal(arg1:string):Promise<void>;

export function PickFolder():Promise<string>;

export function RunBatch(arg1:string,arg2:snapshot.Request):Promise<snapshot.BatchResult>;
