// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnsureTerminalSession(arg1) {
  return window['go']['main']['App']['EnsureTerminalSession'](arg1);
}

export function GenerateCommitMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateCommitMessage'](arg1, arg2, arg3);
}

export function GetCommitDetail(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetCommitDetail'](arg1, arg2, arg3);
}

export function GetRepoHistory(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetRepoHistory'](arg1, arg2, arg3, arg4);
}

export function GetRepoLog(arg1, arg2) {
  return window['go']['main']['App']['GetRepoLog'](arg1, arg2);
}

export function GetSnapshot(arg1) {
  return window['go']['main']['App']['GetSnapshot'](arg1);
}

export function MutateRepo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MutateRepo'](arg1, arg2, arg3, arg4);
}

export function OpenConflicts(arg1) {
  return window['go']['main']['App']['OpenConflicts'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenTerminal(arg1) {
  return window['go']['main']['App']['OpenTerminal'](arg1);
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function RefreshRepo(arg1, arg2) {
  return window['go']['main']['App']['RefreshRepo'](arg1, arg2);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RestartTerminalSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestartTerminalSession'](arg1, arg2, arg3);
}

export function RunBatch(arg1, arg2) {
  return window['go']['main']['App']['RunBatch'](arg1, arg2);
}

export function RunRepoCommand(arg1) {
  return window['go']['main']['App']['RunRepoCommand'](arg1);
}

export function WriteTerminalInput(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminalInput'](arg1, arg2);
}
